/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Mesh extends DeepCloneable {
  private long swigCPtr;

  protected Mesh(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Mesh_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Mesh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Mesh(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Mesh() {
    this(karambaJNI.new_Mesh__SWIG_0(), true);
  }

  public Mesh(Mesh arg, SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    this(karambaJNI.new_Mesh__SWIG_1(Mesh.getCPtr(arg), arg, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict)), true);
  }

  public Mesh(Mesh arg) {
    this(karambaJNI.new_Mesh__SWIG_2(Mesh.getCPtr(arg), arg), true);
  }

  public void copy(Mesh orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    karambaJNI.Mesh_copy__SWIG_0(swigCPtr, this, Mesh.getCPtr(orig), orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
  }

  public void copy(Mesh orig) {
    karambaJNI.Mesh_copy__SWIG_1(swigCPtr, this, Mesh.getCPtr(orig), orig);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Mesh_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Mesh(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.Mesh_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Mesh(cPtr, false);
  }

  public long add(VertexSet face) {
    return karambaJNI.Mesh_add__SWIG_0(swigCPtr, this, VertexSet.getCPtr(face), face);
  }

  public long add(Mesh mesh) {
    return karambaJNI.Mesh_add__SWIG_1(swigCPtr, this, Mesh.getCPtr(mesh), mesh);
  }

  public void finalizeConstruction() {
    karambaJNI.Mesh_finalizeConstruction(swigCPtr, this);
  }

  public long numberOfFaces() {
    return karambaJNI.Mesh_numberOfFaces(swigCPtr, this);
  }

  public VertexSet face(long ind) {
    long cPtr = karambaJNI.Mesh_face__SWIG_0(swigCPtr, this, ind);
    return (cPtr == 0) ? null : new VertexSet(cPtr, false);
  }

  public SWIGTYPE_p_VecIndexes vertexIndexesOfFace(long ind) {
    return new SWIGTYPE_p_VecIndexes(karambaJNI.Mesh_vertexIndexesOfFace(swigCPtr, this, ind), true);
  }

  public SWIGTYPE_p_std__vectorT_geom__VertexSet_p_t faces() {
    return new SWIGTYPE_p_std__vectorT_geom__VertexSet_p_t(karambaJNI.Mesh_faces(swigCPtr, this), false);
  }

  public long numberOfVertexes() {
    return karambaJNI.Mesh_numberOfVertexes(swigCPtr, this);
  }

  public Vertex vertex(long ind) {
    long cPtr = karambaJNI.Mesh_vertex__SWIG_0(swigCPtr, this, ind);
    return (cPtr == 0) ? null : new Vertex(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_geom__Vertex_p_t vertexes() {
    return new SWIGTYPE_p_std__vectorT_geom__Vertex_p_t(karambaJNI.Mesh_vertexes__SWIG_0(swigCPtr, this), false);
  }

  public SWIGTYPE_p_VecIndexes facesOfVertex(long vertex_index) {
    return new SWIGTYPE_p_VecIndexes(karambaJNI.Mesh_facesOfVertex(swigCPtr, this, vertex_index), false);
  }

  public SWIGTYPE_p_VecIndexes facesOfEdge(long n1, long n2) {
    return new SWIGTYPE_p_VecIndexes(karambaJNI.Mesh_facesOfEdge(swigCPtr, this, n1, n2), true);
  }

  public int meshInd(Vertex vert) {
    return karambaJNI.Mesh_meshInd__SWIG_0(swigCPtr, this, Vertex.getCPtr(vert), vert);
  }

  public int meshInd(long vert_id) {
    return karambaJNI.Mesh_meshInd__SWIG_1(swigCPtr, this, vert_id);
  }

}
