/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class DeformThII extends Deform {
  private long swigCPtr;

  protected DeformThII(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.DeformThII_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DeformThII obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_DeformThII(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DeformThII(Model model, int lc, double tol, long max_iter, boolean nii_lt0) {
    this(karambaJNI.new_DeformThII__SWIG_1(Model.getCPtr(model), model, lc, tol, max_iter, nii_lt0), true);
  }

  public DeformThII(Model model, int lc, double tol, long max_iter) {
    this(karambaJNI.new_DeformThII__SWIG_2(Model.getCPtr(model), model, lc, tol, max_iter), true);
  }

  public DeformThII(Model model, int lc, double tol) {
    this(karambaJNI.new_DeformThII__SWIG_3(Model.getCPtr(model), model, lc, tol), true);
  }

  public DeformThII(Model model, int lc) {
    this(karambaJNI.new_DeformThII__SWIG_4(Model.getCPtr(model), model, lc), true);
  }

  public DeformThII(Model model) {
    this(karambaJNI.new_DeformThII__SWIG_5(Model.getCPtr(model), model), true);
  }

  public DeformThII(DeformThII arg) {
    this(karambaJNI.new_DeformThII__SWIG_6(DeformThII.getCPtr(arg), arg), true);
  }

  public Deform clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.DeformThII_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new DeformThII(cPtr, false);
  }

  public Deform clone() {
    long cPtr = karambaJNI.DeformThII_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new DeformThII(cPtr, false);
  }

  public void copy(Deform orig) {
    karambaJNI.DeformThII_copy(swigCPtr, this, Deform.getCPtr(orig), orig);
  }

  public int analyze() {
    return karambaJNI.DeformThII_analyze(swigCPtr, this);
  }

  public boolean converged() {
    return karambaJNI.DeformThII_converged(swigCPtr, this);
  }

  public double convergence_error() {
    return karambaJNI.DeformThII_convergence_error(swigCPtr, this);
  }

}
