/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class DeepCloneable {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public DeepCloneable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DeepCloneable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_DeepCloneable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.DeepCloneable_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new DeepCloneable(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.DeepCloneable_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new DeepCloneable(cPtr, false);
  }

  public DeepCloneable deepclone() {
    long cPtr = karambaJNI.DeepCloneable_deepclone__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new DeepCloneable(cPtr, false);
  }

  public DeepCloneable deepclone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.DeepCloneable_deepclone__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new DeepCloneable(cPtr, false);
  }

  public DeepCloneable() {
    this(karambaJNI.new_DeepCloneable(), true);
  }

}
