/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class CollisionItem {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public CollisionItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CollisionItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_CollisionItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CollisionItem() {
    this(karambaJNI.new_CollisionItem__SWIG_0(), true);
  }

  public CollisionItem(CollisionItem arg) {
    this(karambaJNI.new_CollisionItem__SWIG_1(CollisionItem.getCPtr(arg), arg), true);
  }

  public CollisionItem clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.CollisionItem_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new CollisionItem(cPtr, false);
  }

  public CollisionItem clone() {
    long cPtr = karambaJNI.CollisionItem_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new CollisionItem(cPtr, false);
  }

  public void copy(CollisionItem orig) {
    karambaJNI.CollisionItem_copy(swigCPtr, this, CollisionItem.getCPtr(orig), orig);
  }

  public CollisionItem deepclone() {
    long cPtr = karambaJNI.CollisionItem_deepclone__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new CollisionItem(cPtr, false);
  }

  public CollisionItem deepclone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.CollisionItem_deepclone__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new CollisionItem(cPtr, false);
  }

  public void addTriangle(double x1, double y1, double z1, double x2, double y2, double z2, double x3, double y3, double z3) {
    karambaJNI.CollisionItem_addTriangle(swigCPtr, this, x1, y1, z1, x2, y2, z2, x3, y3, z3);
  }

  public long numberOfCollisions(SWIGTYPE_p_aabb__Tree tree) {
    return karambaJNI.CollisionItem_numberOfCollisions(swigCPtr, this, SWIGTYPE_p_aabb__Tree.getCPtr(tree));
  }

}
