/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class CroSecStateVisitor {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public CroSecStateVisitor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CroSecStateVisitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_CroSecStateVisitor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void visit(SWIGTYPE_p_CroSecDesign__CroSecStateImp_LinearElastic_Beam_EC3_Simplified arg0) {
    karambaJNI.CroSecStateVisitor_visit__SWIG_0(swigCPtr, this, SWIGTYPE_p_CroSecDesign__CroSecStateImp_LinearElastic_Beam_EC3_Simplified.getCPtr(arg0));
  }

  public void visit(SWIGTYPE_p_CroSecDesign__CroSecStateImp_Plastic_Beam_EC3_Simplified arg0) {
    karambaJNI.CroSecStateVisitor_visit__SWIG_1(swigCPtr, this, SWIGTYPE_p_CroSecDesign__CroSecStateImp_Plastic_Beam_EC3_Simplified.getCPtr(arg0));
  }

  public void visit(CroSecStateImp_LinearElastic_Beam_EC3 arg0) {
    karambaJNI.CroSecStateVisitor_visit__SWIG_2(swigCPtr, this, CroSecStateImp_LinearElastic_Beam_EC3.getCPtr(arg0), arg0);
  }

  public void visit(CroSecStateImp_Plastic_Beam_EC3 arg0) {
    karambaJNI.CroSecStateVisitor_visit__SWIG_3(swigCPtr, this, CroSecStateImp_Plastic_Beam_EC3.getCPtr(arg0), arg0);
  }

  public void visit(CroSecStateImp_LinearElastic_Shell arg0) {
    karambaJNI.CroSecStateVisitor_visit__SWIG_4(swigCPtr, this, CroSecStateImp_LinearElastic_Shell.getCPtr(arg0), arg0);
  }

  public void visit(CroSecStateImp_Plastic_Shell arg0) {
    karambaJNI.CroSecStateVisitor_visit__SWIG_5(swigCPtr, this, CroSecStateImp_Plastic_Shell.getCPtr(arg0), arg0);
  }

}
