/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public final class DOF {
  public final static DOF x_t = new DOF("x_t");
  public final static DOF y_t = new DOF("y_t");
  public final static DOF z_t = new DOF("z_t");
  public final static DOF x_r = new DOF("x_r");
  public final static DOF y_r = new DOF("y_r");
  public final static DOF z_r = new DOF("z_r");
  public final static DOF n_dofs = new DOF("n_dofs");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static DOF swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + DOF.class + " with value " + swigValue);
  }

  private DOF(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private DOF(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private DOF(String swigName, DOF swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static DOF[] swigValues = { x_t, y_t, z_t, x_r, y_r, z_r, n_dofs };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

