/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Element extends DeepCloneable {
  private long swigCPtr;

  protected Element(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Element_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Element obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Element(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Element_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.Element_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

  public void copy(Element orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    karambaJNI.Element_copy__SWIG_0(swigCPtr, this, Element.getCPtr(orig), orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
  }

  public void copy(Element orig) {
    karambaJNI.Element_copy__SWIG_1(swigCPtr, this, Element.getCPtr(orig), orig);
  }

  public Node node(long id) {
    return new Node(karambaJNI.Element_node(swigCPtr, this, id), false);
  }

  public void setNode(int id, Node new_node) {
    karambaJNI.Element_setNode(swigCPtr, this, id, Node.getCPtr(new_node), new_node);
  }

  public SWIGTYPE_p_std__vectorT_geom__Vertex_p_t vertexes() {
    return new SWIGTYPE_p_std__vectorT_geom__Vertex_p_t(karambaJNI.Element_vertexes(swigCPtr, this), false);
  }

  public VertexSet vertexSet() {
    long cPtr = karambaJNI.Element_vertexSet(swigCPtr, this);
    return (cPtr == 0) ? null : new VertexSet(cPtr, false);
  }

  public double characteristicLength() {
    return karambaJNI.Element_characteristicLength(swigCPtr, this);
  }

  public double volume() {
    return karambaJNI.Element_volume(swigCPtr, this);
  }

  public double mass() {
    return karambaJNI.Element_mass(swigCPtr, this);
  }

  public double weight_per_unit() {
    return karambaJNI.Element_weight_per_unit(swigCPtr, this);
  }

  public Vec3d direction(long edge_ind) {
    return new Vec3d(karambaJNI.Element_direction__SWIG_0(swigCPtr, this, edge_ind), true);
  }

  public Vec3d direction() {
    return new Vec3d(karambaJNI.Element_direction__SWIG_1(swigCPtr, this), true);
  }

  public boolean openTopology() {
    return karambaJNI.Element_openTopology(swigCPtr, this);
  }

  public Node splitAtNode(Model femodel, Node new_node, double split_tolerance) {
    long cPtr = karambaJNI.Element_splitAtNode__SWIG_0(swigCPtr, this, Model.getCPtr(femodel), femodel, Node.getCPtr(new_node), new_node, split_tolerance);
    return (cPtr == 0) ? null : new Node(cPtr, false);
  }

  public Node splitAtNode(Model femodel, Node new_node) {
    long cPtr = karambaJNI.Element_splitAtNode__SWIG_1(swigCPtr, this, Model.getCPtr(femodel), femodel, Node.getCPtr(new_node), new_node);
    return (cPtr == 0) ? null : new Node(cPtr, false);
  }

  public Node split(Model femodel, double position, double split_tolerance) {
    long cPtr = karambaJNI.Element_split__SWIG_0(swigCPtr, this, Model.getCPtr(femodel), femodel, position, split_tolerance);
    return (cPtr == 0) ? null : new Node(cPtr, false);
  }

  public Node split(Model femodel, double position) {
    long cPtr = karambaJNI.Element_split__SWIG_1(swigCPtr, this, Model.getCPtr(femodel), femodel, position);
    return (cPtr == 0) ? null : new Node(cPtr, false);
  }

  public void add_split_ind(VectElem elems, VectSizeT inds) {
    karambaJNI.Element_add_split_ind(swigCPtr, this, VectElem.getCPtr(elems), elems, VectSizeT.getCPtr(inds), inds);
  }

  public long splitElemInd() {
    return karambaJNI.Element_splitElemInd__SWIG_0(swigCPtr, this);
  }

  public long splitElemInd(int ind) {
    return karambaJNI.Element_splitElemInd__SWIG_1(swigCPtr, this, ind);
  }

  public Vec3d boundaryPoint(Model femodel, long ind) {
    return new Vec3d(karambaJNI.Element_boundaryPoint(swigCPtr, this, Model.getCPtr(femodel), femodel, ind), true);
  }

  public void setActive() {
    karambaJNI.Element_setActive(swigCPtr, this);
  }

  public void setInactive() {
    karambaJNI.Element_setInactive(swigCPtr, this);
  }

  public boolean isActive() {
    return karambaJNI.Element_isActive(swigCPtr, this);
  }

  public SWIGTYPE_p_augMatT_MatSymReal_t elastStiffMatrix_g2g() {
    return new SWIGTYPE_p_augMatT_MatSymReal_t(karambaJNI.Element_elastStiffMatrix_g2g(swigCPtr, this), true);
  }

  public SWIGTYPE_p_augMatT_MatSymReal_t massMatrix_g2g() {
    return new SWIGTYPE_p_augMatT_MatSymReal_t(karambaJNI.Element_massMatrix_g2g(swigCPtr, this), true);
  }

  public SWIGTYPE_p_augMatT_MatSymReal_t geomStiffMatrix_g2g() {
    return new SWIGTYPE_p_augMatT_MatSymReal_t(karambaJNI.Element_geomStiffMatrix_g2g(swigCPtr, this), true);
  }

  public SWIGTYPE_p_augMatT_MatSymReal_t tangentStiffMatrix_g2g() {
    return new SWIGTYPE_p_augMatT_MatSymReal_t(karambaJNI.Element_tangentStiffMatrix_g2g(swigCPtr, this), true);
  }

  public long nNodes() {
    return karambaJNI.Element_nNodes(swigCPtr, this);
  }

  public Vec3d centerPoint() {
    return new Vec3d(karambaJNI.Element_centerPoint(swigCPtr, this), true);
  }

  public long nDofsPerNode() {
    return karambaJNI.Element_nDofsPerNode(swigCPtr, this);
  }

  public long nTranslationalDofsPerNode() {
    return karambaJNI.Element_nTranslationalDofsPerNode(swigCPtr, this);
  }

  public SWIGTYPE_p_VecReal localForce(long lc, long node_ind) {
    return new SWIGTYPE_p_VecReal(karambaJNI.Element_localForce(swigCPtr, this, lc, node_ind), false);
  }

  public SWIGTYPE_p_VecReal localDisp(long lc, long node_ind) {
    return new SWIGTYPE_p_VecReal(karambaJNI.Element_localDisp(swigCPtr, this, lc, node_ind), false);
  }

  public PointState interiorState(long lc, double pos) {
    long cPtr = karambaJNI.Element_interiorState(swigCPtr, this, lc, pos);
    return (cPtr == 0) ? null : new PointState(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_PointState_p_t interiorStates(VectSizeT lc_vec, VectReal pos_vec) {
    return new SWIGTYPE_p_std__vectorT_PointState_p_t(karambaJNI.Element_interiorStates(swigCPtr, this, VectSizeT.getCPtr(lc_vec), lc_vec, VectReal.getCPtr(pos_vec), pos_vec), true);
  }

  public long lcNum() {
    return karambaJNI.Element_lcNum(swigCPtr, this);
  }

  public boolean loadCase_has_weight(long ind) {
    return karambaJNI.Element_loadCase_has_weight(swigCPtr, this, ind);
  }

  public Vec3d loadCase_weight(long ind) {
    return new Vec3d(karambaJNI.Element_loadCase_weight(swigCPtr, this, ind), true);
  }

  public double axialNormalForce(int lc) {
    return karambaJNI.Element_axialNormalForce__SWIG_0(swigCPtr, this, lc);
  }

  public double axialNormalForce() {
    return karambaJNI.Element_axialNormalForce__SWIG_1(swigCPtr, this);
  }

  public double axialStrain(int lc) {
    return karambaJNI.Element_axialStrain__SWIG_0(swigCPtr, this, lc);
  }

  public double axialStrain() {
    return karambaJNI.Element_axialStrain__SWIG_1(swigCPtr, this);
  }

  public VectStrain strain(SWIGTYPE_p_VecReal pos, long lc) {
    return new VectStrain(karambaJNI.Element_strain__SWIG_0(swigCPtr, this, SWIGTYPE_p_VecReal.getCPtr(pos), lc), true);
  }

  public VectStrain strain(SWIGTYPE_p_VecReal pos) {
    return new VectStrain(karambaJNI.Element_strain__SWIG_1(swigCPtr, this, SWIGTYPE_p_VecReal.getCPtr(pos)), true);
  }

  public CroSecStrain strain(long lc) {
    return new CroSecStrain(karambaJNI.Element_strain__SWIG_2(swigCPtr, this, lc), true);
  }

  public CroSecStrain strain() {
    return new CroSecStrain(karambaJNI.Element_strain__SWIG_3(swigCPtr, this), true);
  }

  public double maxInteriorDeflection(int lc) {
    return karambaJNI.Element_maxInteriorDeflection__SWIG_0(swigCPtr, this, lc);
  }

  public double maxInteriorDeflection() {
    return karambaJNI.Element_maxInteriorDeflection__SWIG_1(swigCPtr, this);
  }

  public VectVec3d deflection(SWIGTYPE_p_VecReal pos, int lc) {
    return new VectVec3d(karambaJNI.Element_deflection__SWIG_0(swigCPtr, this, SWIGTYPE_p_VecReal.getCPtr(pos), lc), true);
  }

  public VectVec3d deflection(SWIGTYPE_p_VecReal pos) {
    return new VectVec3d(karambaJNI.Element_deflection__SWIG_1(swigCPtr, this, SWIGTYPE_p_VecReal.getCPtr(pos)), true);
  }

  public CooSys coosys() {
    long cPtr = karambaJNI.Element_coosys(swigCPtr, this);
    return (cPtr == 0) ? null : new CooSys(cPtr, false);
  }

  public void updatePosition() {
    karambaJNI.Element_updatePosition(swigCPtr, this);
  }

  public void updateCooSys() {
    karambaJNI.Element_updateCooSys(swigCPtr, this);
  }

  public Vec3d pointOnAxis(double pos, boolean with_ecce) {
    return new Vec3d(karambaJNI.Element_pointOnAxis__SWIG_0(swigCPtr, this, pos, with_ecce), true);
  }

  public Vec3d pointOnAxis(double pos) {
    return new Vec3d(karambaJNI.Element_pointOnAxis__SWIG_1(swigCPtr, this, pos), true);
  }

  public VectVec3d pointsOnAxis(long n, boolean with_ecce) {
    return new VectVec3d(karambaJNI.Element_pointsOnAxis__SWIG_0(swigCPtr, this, n, with_ecce), true);
  }

  public VectVec3d pointsOnAxis(long n) {
    return new VectVec3d(karambaJNI.Element_pointsOnAxis__SWIG_1(swigCPtr, this, n), true);
  }

  public VectVec3d pointsOnAxis() {
    return new VectVec3d(karambaJNI.Element_pointsOnAxis__SWIG_2(swigCPtr, this), true);
  }

  public void addDeflection(VectVec3d p, long lc, double factor) {
    karambaJNI.Element_addDeflection__SWIG_0(swigCPtr, this, VectVec3d.getCPtr(p), p, lc, factor);
  }

  public void addDeflection(VectVec3d p, long lc) {
    karambaJNI.Element_addDeflection__SWIG_1(swigCPtr, this, VectVec3d.getCPtr(p), p, lc);
  }

  public VectStrain strainsOnAxis(long n, long lc) {
    return new VectStrain(karambaJNI.Element_strainsOnAxis(swigCPtr, this, n, lc), true);
  }

  public double axialDeformationEnergy(int lc) {
    return karambaJNI.Element_axialDeformationEnergy__SWIG_0(swigCPtr, this, lc);
  }

  public double axialDeformationEnergy() {
    return karambaJNI.Element_axialDeformationEnergy__SWIG_1(swigCPtr, this);
  }

  public double bendingEnergy(int lc) {
    return karambaJNI.Element_bendingEnergy__SWIG_0(swigCPtr, this, lc);
  }

  public double bendingEnergy() {
    return karambaJNI.Element_bendingEnergy__SWIG_1(swigCPtr, this);
  }

  public double elastEnergy(int lc) {
    return karambaJNI.Element_elastEnergy__SWIG_0(swigCPtr, this, lc);
  }

  public double elastEnergy() {
    return karambaJNI.Element_elastEnergy__SWIG_1(swigCPtr, this);
  }

  public double work(int lc1, int lc2) {
    return karambaJNI.Element_work__SWIG_0(swigCPtr, this, lc1, lc2);
  }

  public double work(int lc1) {
    return karambaJNI.Element_work__SWIG_1(swigCPtr, this, lc1);
  }

  public double work() {
    return karambaJNI.Element_work__SWIG_2(swigCPtr, this);
  }

  public ElementCroSec crosec() {
    return new ElementCroSec(karambaJNI.Element_crosec__SWIG_0(swigCPtr, this), false);
  }

  public ElementCroSec crosec(ElementCroSec p) {
    return new ElementCroSec(karambaJNI.Element_crosec__SWIG_1(swigCPtr, this, ElementCroSec.getCPtr(p), p), false);
  }

  public Material material() {
    return new Material(karambaJNI.Element_material__SWIG_0(swigCPtr, this), false);
  }

  public Material material(Material mat) {
    return new Material(karambaJNI.Element_material__SWIG_1(swigCPtr, this, Material.getCPtr(mat), mat), false);
  }

  public Eccentricity eccNum(long ind) {
    return new Eccentricity(karambaJNI.Element_eccNum__SWIG_0(swigCPtr, this, ind), false);
  }

  public Eccentricity eccNum(long ind, Eccentricity ecce) {
    return new Eccentricity(karambaJNI.Element_eccNum__SWIG_1(swigCPtr, this, ind, Eccentricity.getCPtr(ecce), ecce), false);
  }

  public boolean allowIntersection() {
    return karambaJNI.Element_allowIntersection__SWIG_0(swigCPtr, this);
  }

  public boolean allowIntersection(boolean flg) {
    return karambaJNI.Element_allowIntersection__SWIG_1(swigCPtr, this, flg);
  }

  public void clearLoads() {
    karambaJNI.Element_clearLoads(swigCPtr, this);
  }

  public void initState(long lc_num) {
    karambaJNI.Element_initState(swigCPtr, this, lc_num);
  }

  public void updateFext(SWIGTYPE_p_VecLCModel load_cases, double lambda) {
    karambaJNI.Element_updateFext__SWIG_0(swigCPtr, this, SWIGTYPE_p_VecLCModel.getCPtr(load_cases), lambda);
  }

  public void updateFext(SWIGTYPE_p_VecLCModel load_cases) {
    karambaJNI.Element_updateFext__SWIG_1(swigCPtr, this, SWIGTYPE_p_VecLCModel.getCPtr(load_cases));
  }

  public void updateDeadWeight(VectReal dead_weights, SWIGTYPE_p_VecLCModel load_cases) {
    karambaJNI.Element_updateDeadWeight(swigCPtr, this, VectReal.getCPtr(dead_weights), dead_weights, SWIGTYPE_p_VecLCModel.getCPtr(load_cases));
  }

  public void updateDisplacements() {
    karambaJNI.Element_updateDisplacements(swigCPtr, this);
  }

  public void updateFint() {
    karambaJNI.Element_updateFint(swigCPtr, this);
  }

  public void add(long lc, Load load) {
    karambaJNI.Element_add(swigCPtr, this, lc, Load.getCPtr(load), load);
  }

  public long ind(long new_ind) {
    return karambaJNI.Element_ind__SWIG_0(swigCPtr, this, new_ind);
  }

  public long ind() {
    return karambaJNI.Element_ind__SWIG_1(swigCPtr, this);
  }

  public int id_num(int ind) {
    return karambaJNI.Element_id_num__SWIG_0(swigCPtr, this, ind);
  }

  public int id_num() {
    return karambaJNI.Element_id_num__SWIG_1(swigCPtr, this);
  }

  public void accept(ElementVisitor visitor) {
    karambaJNI.Element_accept(swigCPtr, this, ElementVisitor.getCPtr(visitor), visitor);
  }

  public VectReal SWIG_localForceState(int lc, int node_ind) {
    return new VectReal(karambaJNI.Element_SWIG_localForceState(swigCPtr, this, lc, node_ind), true);
  }

  public int SWIG_typeid() {
    return karambaJNI.Element_SWIG_typeid(swigCPtr, this);
  }

  public double SWIG_NII_value() {
    return karambaJNI.Element_SWIG_NII_value(swigCPtr, this);
  }

}
