/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Element_Impl extends Element {
  private long swigCPtr;

  protected Element_Impl(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Element_Impl_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Element_Impl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Element_Impl(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void copy(Element orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    karambaJNI.Element_Impl_copy__SWIG_0(swigCPtr, this, Element.getCPtr(orig), orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
  }

  public void copy(Element orig) {
    karambaJNI.Element_Impl_copy__SWIG_1(swigCPtr, this, Element.getCPtr(orig), orig);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Element_Impl_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Element_Impl(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.Element_Impl_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Element_Impl(cPtr, false);
  }

  public Node node(long id) {
    return new Node(karambaJNI.Element_Impl_node(swigCPtr, this, id), false);
  }

  public void setNode(int id, Node new_node) {
    karambaJNI.Element_Impl_setNode(swigCPtr, this, id, Node.getCPtr(new_node), new_node);
  }

  public SWIGTYPE_p_std__vectorT_geom__Vertex_p_t vertexes() {
    return new SWIGTYPE_p_std__vectorT_geom__Vertex_p_t(karambaJNI.Element_Impl_vertexes(swigCPtr, this), false);
  }

  public VertexSet vertexSet() {
    long cPtr = karambaJNI.Element_Impl_vertexSet(swigCPtr, this);
    return (cPtr == 0) ? null : new VertexSet(cPtr, false);
  }

  public double weight_per_unit() {
    return karambaJNI.Element_Impl_weight_per_unit(swigCPtr, this);
  }

  public boolean openTopology() {
    return karambaJNI.Element_Impl_openTopology(swigCPtr, this);
  }

  public Vec3d direction(long edge_ind) {
    return new Vec3d(karambaJNI.Element_Impl_direction__SWIG_0(swigCPtr, this, edge_ind), true);
  }

  public Vec3d direction() {
    return new Vec3d(karambaJNI.Element_Impl_direction__SWIG_1(swigCPtr, this), true);
  }

  public Vec3d centerPoint() {
    return new Vec3d(karambaJNI.Element_Impl_centerPoint(swigCPtr, this), true);
  }

  public void add_split_ind(VectElem elems, VectSizeT inds) {
    karambaJNI.Element_Impl_add_split_ind(swigCPtr, this, VectElem.getCPtr(elems), elems, VectSizeT.getCPtr(inds), inds);
  }

  public long splitElemInd() {
    return karambaJNI.Element_Impl_splitElemInd__SWIG_0(swigCPtr, this);
  }

  public long splitElemInd(int ind) {
    return karambaJNI.Element_Impl_splitElemInd__SWIG_1(swigCPtr, this, ind);
  }

  public Vec3d boundaryPoint(Model femodel, long ind) {
    return new Vec3d(karambaJNI.Element_Impl_boundaryPoint(swigCPtr, this, Model.getCPtr(femodel), femodel, ind), true);
  }

  public long ind(long new_ind) {
    return karambaJNI.Element_Impl_ind__SWIG_0(swigCPtr, this, new_ind);
  }

  public long ind() {
    return karambaJNI.Element_Impl_ind__SWIG_1(swigCPtr, this);
  }

  public void setActive() {
    karambaJNI.Element_Impl_setActive(swigCPtr, this);
  }

  public void setInactive() {
    karambaJNI.Element_Impl_setInactive(swigCPtr, this);
  }

  public boolean isActive() {
    return karambaJNI.Element_Impl_isActive(swigCPtr, this);
  }

  public long nNodes() {
    return karambaJNI.Element_Impl_nNodes(swigCPtr, this);
  }

  public SWIGTYPE_p_VecReal localForce(long lc, long node_ind) {
    return new SWIGTYPE_p_VecReal(karambaJNI.Element_Impl_localForce(swigCPtr, this, lc, node_ind), false);
  }

  public SWIGTYPE_p_VecReal localDisp(long lc, long node_ind) {
    return new SWIGTYPE_p_VecReal(karambaJNI.Element_Impl_localDisp(swigCPtr, this, lc, node_ind), false);
  }

  public long lcNum() {
    return karambaJNI.Element_Impl_lcNum(swigCPtr, this);
  }

  public double axialNormalForce(int lc) {
    return karambaJNI.Element_Impl_axialNormalForce__SWIG_0(swigCPtr, this, lc);
  }

  public double axialNormalForce() {
    return karambaJNI.Element_Impl_axialNormalForce__SWIG_1(swigCPtr, this);
  }

  public double axialStrain(int lc) {
    return karambaJNI.Element_Impl_axialStrain__SWIG_0(swigCPtr, this, lc);
  }

  public double axialStrain() {
    return karambaJNI.Element_Impl_axialStrain__SWIG_1(swigCPtr, this);
  }

  public VectStrain strain(SWIGTYPE_p_VecReal pos, long lc) {
    return new VectStrain(karambaJNI.Element_Impl_strain__SWIG_0(swigCPtr, this, SWIGTYPE_p_VecReal.getCPtr(pos), lc), true);
  }

  public VectStrain strain(SWIGTYPE_p_VecReal pos) {
    return new VectStrain(karambaJNI.Element_Impl_strain__SWIG_1(swigCPtr, this, SWIGTYPE_p_VecReal.getCPtr(pos)), true);
  }

  public CroSecStrain strain(long lc) {
    return new CroSecStrain(karambaJNI.Element_Impl_strain__SWIG_2(swigCPtr, this, lc), true);
  }

  public CroSecStrain strain() {
    return new CroSecStrain(karambaJNI.Element_Impl_strain__SWIG_3(swigCPtr, this), true);
  }

  public double maxInteriorDeflection(int lc) {
    return karambaJNI.Element_Impl_maxInteriorDeflection__SWIG_0(swigCPtr, this, lc);
  }

  public double maxInteriorDeflection() {
    return karambaJNI.Element_Impl_maxInteriorDeflection__SWIG_1(swigCPtr, this);
  }

  public VectVec3d deflection(SWIGTYPE_p_VecReal pos, int lc) {
    return new VectVec3d(karambaJNI.Element_Impl_deflection__SWIG_0(swigCPtr, this, SWIGTYPE_p_VecReal.getCPtr(pos), lc), true);
  }

  public VectVec3d deflection(SWIGTYPE_p_VecReal pos) {
    return new VectVec3d(karambaJNI.Element_Impl_deflection__SWIG_1(swigCPtr, this, SWIGTYPE_p_VecReal.getCPtr(pos)), true);
  }

  public void updatePosition() {
    karambaJNI.Element_Impl_updatePosition(swigCPtr, this);
  }

  public VectStrain strainsOnAxis(long n, long lc) {
    return new VectStrain(karambaJNI.Element_Impl_strainsOnAxis(swigCPtr, this, n, lc), true);
  }

  public double axialDeformationEnergy(int lc) {
    return karambaJNI.Element_Impl_axialDeformationEnergy__SWIG_0(swigCPtr, this, lc);
  }

  public double axialDeformationEnergy() {
    return karambaJNI.Element_Impl_axialDeformationEnergy__SWIG_1(swigCPtr, this);
  }

  public double bendingEnergy(int lc) {
    return karambaJNI.Element_Impl_bendingEnergy__SWIG_0(swigCPtr, this, lc);
  }

  public double bendingEnergy() {
    return karambaJNI.Element_Impl_bendingEnergy__SWIG_1(swigCPtr, this);
  }

  public double elastEnergy(int lc) {
    return karambaJNI.Element_Impl_elastEnergy__SWIG_0(swigCPtr, this, lc);
  }

  public double elastEnergy() {
    return karambaJNI.Element_Impl_elastEnergy__SWIG_1(swigCPtr, this);
  }

  public double work(int lc1, int lc2) {
    return karambaJNI.Element_Impl_work__SWIG_0(swigCPtr, this, lc1, lc2);
  }

  public double work(int lc1) {
    return karambaJNI.Element_Impl_work__SWIG_1(swigCPtr, this, lc1);
  }

  public double work() {
    return karambaJNI.Element_Impl_work__SWIG_2(swigCPtr, this);
  }

  public Material material() {
    return new Material(karambaJNI.Element_Impl_material__SWIG_0(swigCPtr, this), false);
  }

  public Material material(Material mat) {
    return new Material(karambaJNI.Element_Impl_material__SWIG_1(swigCPtr, this, Material.getCPtr(mat), mat), false);
  }

  public Eccentricity eccNum(long ind) {
    return new Eccentricity(karambaJNI.Element_Impl_eccNum__SWIG_0(swigCPtr, this, ind), false);
  }

  public Eccentricity eccNum(long ind, Eccentricity ecce) {
    return new Eccentricity(karambaJNI.Element_Impl_eccNum__SWIG_1(swigCPtr, this, ind, Eccentricity.getCPtr(ecce), ecce), false);
  }

  public boolean allowIntersection() {
    return karambaJNI.Element_Impl_allowIntersection__SWIG_0(swigCPtr, this);
  }

  public boolean allowIntersection(boolean flg) {
    return karambaJNI.Element_Impl_allowIntersection__SWIG_1(swigCPtr, this, flg);
  }

  public void updateFext(SWIGTYPE_p_VecLCModel load_cases, double lambda) {
    karambaJNI.Element_Impl_updateFext__SWIG_0(swigCPtr, this, SWIGTYPE_p_VecLCModel.getCPtr(load_cases), lambda);
  }

  public void updateFext(SWIGTYPE_p_VecLCModel load_cases) {
    karambaJNI.Element_Impl_updateFext__SWIG_1(swigCPtr, this, SWIGTYPE_p_VecLCModel.getCPtr(load_cases));
  }

  public void updateDeadWeight(VectReal dead_weights, SWIGTYPE_p_VecLCModel load_cases) {
    karambaJNI.Element_Impl_updateDeadWeight(swigCPtr, this, VectReal.getCPtr(dead_weights), dead_weights, SWIGTYPE_p_VecLCModel.getCPtr(load_cases));
  }

  public void updateFint() {
    karambaJNI.Element_Impl_updateFint(swigCPtr, this);
  }

  public boolean loadCase_has_weight(long ind) {
    return karambaJNI.Element_Impl_loadCase_has_weight(swigCPtr, this, ind);
  }

  public Vec3d loadCase_weight(long ind) {
    return new Vec3d(karambaJNI.Element_Impl_loadCase_weight(swigCPtr, this, ind), true);
  }

  public void clearLoads() {
    karambaJNI.Element_Impl_clearLoads(swigCPtr, this);
  }

  public void add(long lc, Load load) {
    karambaJNI.Element_Impl_add(swigCPtr, this, lc, Load.getCPtr(load), load);
  }

  public int id_num(int ind) {
    return karambaJNI.Element_Impl_id_num__SWIG_0(swigCPtr, this, ind);
  }

  public int id_num() {
    return karambaJNI.Element_Impl_id_num__SWIG_1(swigCPtr, this);
  }

  public VectReal SWIG_localForceState(int lc, int node_ind) {
    return new VectReal(karambaJNI.Element_Impl_SWIG_localForceState(swigCPtr, this, lc, node_ind), true);
  }

  public int SWIG_typeid() {
    return karambaJNI.Element_Impl_SWIG_typeid(swigCPtr, this);
  }

  public double SWIG_NII_value() {
    return karambaJNI.Element_Impl_SWIG_NII_value(swigCPtr, this);
  }

}
