/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ProxyStitch extends Stitch {
  private long swigCPtr;

  protected ProxyStitch(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.ProxyStitch_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProxyStitch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ProxyStitch(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ProxyStitch(long n_connections, ElementStraightLine elem, double min_offset, double max_offset) {
    this(karambaJNI.new_ProxyStitch__SWIG_1(n_connections, ElementStraightLine.getCPtr(elem), elem, min_offset, max_offset), true);
  }

  public ProxyStitch(long n_connections, ElementStraightLine elem, double min_offset) {
    this(karambaJNI.new_ProxyStitch__SWIG_2(n_connections, ElementStraightLine.getCPtr(elem), elem, min_offset), true);
  }

  public ProxyStitch(long n_connections, ElementStraightLine elem) {
    this(karambaJNI.new_ProxyStitch__SWIG_3(n_connections, ElementStraightLine.getCPtr(elem), elem), true);
  }

  public ProxyStitch(SWIGTYPE_p_std__vectorT_PolyElement_p_t edges, int n_connections, ElementStraightLine elem, double min_offset, double max_offset) {
    this(karambaJNI.new_ProxyStitch__SWIG_4(SWIGTYPE_p_std__vectorT_PolyElement_p_t.getCPtr(edges), n_connections, ElementStraightLine.getCPtr(elem), elem, min_offset, max_offset), true);
  }

  public ProxyStitch(SWIGTYPE_p_std__vectorT_PolyElement_p_t edges, int n_connections, ElementStraightLine elem, double min_offset) {
    this(karambaJNI.new_ProxyStitch__SWIG_5(SWIGTYPE_p_std__vectorT_PolyElement_p_t.getCPtr(edges), n_connections, ElementStraightLine.getCPtr(elem), elem, min_offset), true);
  }

  public ProxyStitch(SWIGTYPE_p_std__vectorT_PolyElement_p_t edges, int n_connections, ElementStraightLine elem) {
    this(karambaJNI.new_ProxyStitch__SWIG_6(SWIGTYPE_p_std__vectorT_PolyElement_p_t.getCPtr(edges), n_connections, ElementStraightLine.getCPtr(elem), elem), true);
  }

  public ProxyStitch(ProxyStitch arg) {
    this(karambaJNI.new_ProxyStitch__SWIG_7(ProxyStitch.getCPtr(arg), arg), true);
  }

  public GeMapping clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.ProxyStitch_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new ProxyStitch(cPtr, false);
  }

  public GeMapping clone() {
    long cPtr = karambaJNI.ProxyStitch_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ProxyStitch(cPtr, false);
  }

  public void copy(ProxyStitch orig) {
    karambaJNI.ProxyStitch_copy(swigCPtr, this, ProxyStitch.getCPtr(orig), orig);
  }

  public void map(GeModel gemodel, SWIGTYPE_p_std__vectorT_double_t__const_iterator params_begin, SWIGTYPE_p_std__vectorT_double_t__const_iterator params_end) {
    karambaJNI.ProxyStitch_map(swigCPtr, this, GeModel.getCPtr(gemodel), gemodel, SWIGTYPE_p_std__vectorT_double_t__const_iterator.getCPtr(params_begin), SWIGTYPE_p_std__vectorT_double_t__const_iterator.getCPtr(params_end));
  }

}
