/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Surface3DVecEvalStrategy {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public Surface3DVecEvalStrategy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Surface3DVecEvalStrategy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Surface3DVecEvalStrategy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_tvmet__VectorT_real_2_t res(TriShell3D elem) {
    return new SWIGTYPE_p_tvmet__VectorT_real_2_t(karambaJNI.Surface3DVecEvalStrategy_res(swigCPtr, this, TriShell3D.getCPtr(elem), elem), true);
  }

  public void setLC(long lc) {
    karambaJNI.Surface3DVecEvalStrategy_setLC(swigCPtr, this, lc);
  }

}
