/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class GeMapping {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public GeMapping(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GeMapping obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_GeMapping(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GeMapping clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.GeMapping_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new GeMapping(cPtr, false);
  }

  public GeMapping clone() {
    long cPtr = karambaJNI.GeMapping_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new GeMapping(cPtr, false);
  }

  public void copy(GeMapping orig) {
    karambaJNI.GeMapping_copy(swigCPtr, this, GeMapping.getCPtr(orig), orig);
  }

  public long parametersPerConnection() {
    return karambaJNI.GeMapping_parametersPerConnection(swigCPtr, this);
  }

  public long numberOfParameters() {
    return karambaJNI.GeMapping_numberOfParameters(swigCPtr, this);
  }

  public void map(GeModel gemodel, SWIGTYPE_p_std__vectorT_double_t__const_iterator params_begin, SWIGTYPE_p_std__vectorT_double_t__const_iterator params_end) {
    karambaJNI.GeMapping_map(swigCPtr, this, GeModel.getCPtr(gemodel), gemodel, SWIGTYPE_p_std__vectorT_double_t__const_iterator.getCPtr(params_begin), SWIGTYPE_p_std__vectorT_double_t__const_iterator.getCPtr(params_end));
  }

}
