/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public interface karambaConstants {
  public final static double SMALL_NUM = karambaJNI.SMALL_NUM_get();
  public final static double SMALL_NUM3 = karambaJNI.SMALL_NUM3_get();
  public final static double DEFAULT_SPLIT_TOLERANCE = karambaJNI.DEFAULT_SPLIT_TOLERANCE_get();
  public final static double ABS_BEAM_LENGTH_LIMIT = karambaJNI.ABS_BEAM_LENGTH_LIMIT_get();
  public final static double REL_BEAM_LENGTH_LIMIT = karambaJNI.REL_BEAM_LENGTH_LIMIT_get();
  public final static int TRIALVERSION_MAX_BEAMS = karambaJNI.TRIALVERSION_MAX_BEAMS_get();
  public final static int TRIALVERSION_MAX_SHELLS = karambaJNI.TRIALVERSION_MAX_SHELLS_get();
}
