/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class PointStateTrans extends PointState {
  private long swigCPtr;

  protected PointStateTrans(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.PointStateTrans_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PointStateTrans obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_PointStateTrans(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PointStateTrans() {
    this(karambaJNI.new_PointStateTrans__SWIG_0(), true);
  }

  public PointStateTrans(CooSys coosys) {
    this(karambaJNI.new_PointStateTrans__SWIG_1(CooSys.getCPtr(coosys), coosys), true);
  }

  public PointStateTrans(PointStateTrans arg, SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    this(karambaJNI.new_PointStateTrans__SWIG_2(PointStateTrans.getCPtr(arg), arg, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict)), true);
  }

  public PointStateTrans(PointStateTrans arg) {
    this(karambaJNI.new_PointStateTrans__SWIG_3(PointStateTrans.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.PointStateTrans_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new PointStateTrans(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.PointStateTrans_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new PointStateTrans(cPtr, false);
  }

  public void copy(PointState orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    karambaJNI.PointStateTrans_copy__SWIG_0(swigCPtr, this, PointState.getCPtr(orig), orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
  }

  public void copy(PointState orig) {
    karambaJNI.PointStateTrans_copy__SWIG_1(swigCPtr, this, PointState.getCPtr(orig), orig);
  }

  public Vec3d dispTransGlobal() {
    return new Vec3d(karambaJNI.PointStateTrans_dispTransGlobal(swigCPtr, this), true);
  }

}
