/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class VectTriShell3D {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public VectTriShell3D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectTriShell3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_VectTriShell3D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectTriShell3D() {
    this(karambaJNI.new_VectTriShell3D__SWIG_0(), true);
  }

  public VectTriShell3D(long n) {
    this(karambaJNI.new_VectTriShell3D__SWIG_1(n), true);
  }

  public long size() {
    return karambaJNI.VectTriShell3D_size(swigCPtr, this);
  }

  public long capacity() {
    return karambaJNI.VectTriShell3D_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    karambaJNI.VectTriShell3D_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return karambaJNI.VectTriShell3D_isEmpty(swigCPtr, this);
  }

  public void clear() {
    karambaJNI.VectTriShell3D_clear(swigCPtr, this);
  }

  public void add(TriShell3D x) {
    karambaJNI.VectTriShell3D_add(swigCPtr, this, TriShell3D.getCPtr(x), x);
  }

  public TriShell3D get(int i) {
    long cPtr = karambaJNI.VectTriShell3D_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new TriShell3D(cPtr, false);
  }

  public void set(int i, TriShell3D val) {
    karambaJNI.VectTriShell3D_set(swigCPtr, this, i, TriShell3D.getCPtr(val), val);
  }

}
