/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class SWIGTYPE_p_order__kdtree2 {
  private long swigCPtr;

  protected SWIGTYPE_p_order__kdtree2(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_order__kdtree2() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_order__kdtree2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

