/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Beam3DLoadInfo extends Truss3DLoadInfo {
  private long swigCPtr;

  protected Beam3DLoadInfo(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Beam3DLoadInfo_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Beam3DLoadInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Beam3DLoadInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Beam3DLoadInfo(double length, double nII, double E, double G, double Iy, double Iz, double ky, double kz, double Ay, double Az) {
    this(karambaJNI.new_Beam3DLoadInfo(length, nII, E, G, Iy, Iz, ky, kz, Ay, Az), true);
  }

  public VectReal bjy() {
    return new VectReal(karambaJNI.Beam3DLoadInfo_bjy(swigCPtr, this), false);
  }

  public VectReal bjz() {
    return new VectReal(karambaJNI.Beam3DLoadInfo_bjz(swigCPtr, this), false);
  }

  public double invEIy() {
    return karambaJNI.Beam3DLoadInfo_invEIy(swigCPtr, this);
  }

  public double invGAz() {
    return karambaJNI.Beam3DLoadInfo_invGAz(swigCPtr, this);
  }

  public double invEIz() {
    return karambaJNI.Beam3DLoadInfo_invEIz(swigCPtr, this);
  }

  public double invGAy() {
    return karambaJNI.Beam3DLoadInfo_invGAy(swigCPtr, this);
  }

  public void setPos(double pos) {
    karambaJNI.Beam3DLoadInfo_setPos(swigCPtr, this, pos);
  }

}
