/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class NeaerstElementDirectionStrategy extends ElementDirectionStrategy {
  private long swigCPtr;

  protected NeaerstElementDirectionStrategy(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.NeaerstElementDirectionStrategy_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NeaerstElementDirectionStrategy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_NeaerstElementDirectionStrategy(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NeaerstElementDirectionStrategy(VectVec3d dirs, VectVec3d pos, VectTriShell3D elems, SWIGTYPE_p_std__vectorT_geom__Vertex_p_t nodes) {
    this(karambaJNI.new_NeaerstElementDirectionStrategy(VectVec3d.getCPtr(dirs), dirs, VectVec3d.getCPtr(pos), pos, VectTriShell3D.getCPtr(elems), elems, SWIGTYPE_p_std__vectorT_geom__Vertex_p_t.getCPtr(nodes)), true);
  }

  public Vec3d elementDir(long i) {
    return new Vec3d(karambaJNI.NeaerstElementDirectionStrategy_elementDir(swigCPtr, this, i), false);
  }

}
