/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class PointCloud3d {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public PointCloud3d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PointCloud3d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_PointCloud3d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static public class Point {
    private long swigCPtr;
    public boolean swigCMemOwn;
  
    public Point(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    public static long getCPtr(Point obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          karambaJNI.delete_PointCloud3d_Point(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public Point(double _x, double _y, double _z) {
      this(karambaJNI.new_PointCloud3d_Point(_x, _y, _z), true);
    }
  
    public void setV(SWIGTYPE_p_double value) {
      karambaJNI.PointCloud3d_Point_v_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
    }
  
    public SWIGTYPE_p_double getV() {
      long cPtr = karambaJNI.PointCloud3d_Point_v_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
    }
  
  }

  public void setPts(SWIGTYPE_p_std__vectorT_PointCloud3d__Point_t value) {
    karambaJNI.PointCloud3d_pts_set(swigCPtr, this, SWIGTYPE_p_std__vectorT_PointCloud3d__Point_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__vectorT_PointCloud3d__Point_t getPts() {
    long cPtr = karambaJNI.PointCloud3d_pts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__vectorT_PointCloud3d__Point_t(cPtr, false);
  }

  public long kdtree_get_point_count() {
    return karambaJNI.PointCloud3d_kdtree_get_point_count(swigCPtr, this);
  }

  public double kdtree_distance(SWIGTYPE_p_double p1, long idx_p2, long size) {
    return karambaJNI.PointCloud3d_kdtree_distance(swigCPtr, this, SWIGTYPE_p_double.getCPtr(p1), idx_p2, size);
  }

  public double kdtree_get_pt(long idx, int dim) {
    return karambaJNI.PointCloud3d_kdtree_get_pt(swigCPtr, this, idx, dim);
  }

  public PointCloud3d() {
    this(karambaJNI.new_PointCloud3d(), true);
  }

}
