/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Surface3DResultants {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public Surface3DResultants(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Surface3DResultants obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Surface3DResultants(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Surface3DResultants() {
    this(karambaJNI.new_Surface3DResultants__SWIG_0(), true);
  }

  public Surface3DResultants(Vec3d N, Vec3d M, Vec3d V) {
    this(karambaJNI.new_Surface3DResultants__SWIG_1(Vec3d.getCPtr(N), N, Vec3d.getCPtr(M), M, Vec3d.getCPtr(V), V), true);
  }

  public Surface3DResultants clone() {
    long cPtr = karambaJNI.Surface3DResultants_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Surface3DResultants(cPtr, false);
  }

  public void copy(Surface3DResultants orig) {
    karambaJNI.Surface3DResultants_copy(swigCPtr, this, Surface3DResultants.getCPtr(orig), orig);
  }

  public Vec3d M() {
    return new Vec3d(karambaJNI.Surface3DResultants_M(swigCPtr, this), true);
  }

  public Vec3d N() {
    return new Vec3d(karambaJNI.Surface3DResultants_N(swigCPtr, this), true);
  }

  public Vec3d V() {
    return new Vec3d(karambaJNI.Surface3DResultants_V(swigCPtr, this), true);
  }

  public void add(Surface3DResultants other) {
    karambaJNI.Surface3DResultants_add(swigCPtr, this, Surface3DResultants.getCPtr(other), other);
  }

}
