/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class karamba implements karambaConstants {
  public static String getRequired_lic_version() {
    return karambaJNI.required_lic_version_get();
  }

  public static double squared_distance(Vec3d vec1, Vec3d vec2) {
    return karambaJNI.squared_distance(Vec3d.getCPtr(vec1), vec1, Vec3d.getCPtr(vec2), vec2);
  }

  public static SWIGTYPE_p_Mat33 rotationMatrix(double phix, double phiy, double phiz) {
    return new SWIGTYPE_p_Mat33(karambaJNI.rotationMatrix(phix, phiy, phiz), true);
  }

  public static SWIGTYPE_p_VecReal prod(SWIGTYPE_p_Mat33 Ti, SWIGTYPE_p_VecReal v) {
    return new SWIGTYPE_p_VecReal(karambaJNI.prod(SWIGTYPE_p_Mat33.getCPtr(Ti), SWIGTYPE_p_VecReal.getCPtr(v)), true);
  }

  public static double getPenalty_fac() {
    return karambaJNI.penalty_fac_get();
  }

  public static int getAll_loadcases() {
    return karambaJNI.all_loadcases_get();
  }

  public static int getMAX_NUM_INTERSECTIONS() {
    return karambaJNI.MAX_NUM_INTERSECTIONS_get();
  }

  public static int getNO_EXCENTRICITY() {
    return karambaJNI.NO_EXCENTRICITY_get();
  }

}
