/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ElementCroSec extends DeepCloneable {
  private long swigCPtr;

  protected ElementCroSec(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.ElementCroSec_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ElementCroSec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ElementCroSec(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.ElementCroSec_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new ElementCroSec(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.ElementCroSec_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ElementCroSec(cPtr, false);
  }

  public void copy(ElementCroSec orig) {
    karambaJNI.ElementCroSec_copy(swigCPtr, this, ElementCroSec.getCPtr(orig), orig);
  }

  public boolean strongerThan(ElementCroSec other) {
    return karambaJNI.ElementCroSec_strongerThan(swigCPtr, this, ElementCroSec.getCPtr(other), other);
  }

  public void setFamily(int value) {
    karambaJNI.ElementCroSec_family_set(swigCPtr, this, value);
  }

  public int getFamily() {
    return karambaJNI.ElementCroSec_family_get(swigCPtr, this);
  }

  public void setId(int value) {
    karambaJNI.ElementCroSec_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return karambaJNI.ElementCroSec_id_get(swigCPtr, this);
  }

  public long ind(long new_ind) {
    return karambaJNI.ElementCroSec_ind__SWIG_0(swigCPtr, this, new_ind);
  }

  public long ind() {
    return karambaJNI.ElementCroSec_ind__SWIG_1(swigCPtr, this);
  }

  public Vec3d eccentricity() {
    return new Vec3d(karambaJNI.ElementCroSec_eccentricity__SWIG_0(swigCPtr, this), true);
  }

  public Vec3d eccentricity(Vec3d ecc) {
    return new Vec3d(karambaJNI.ElementCroSec_eccentricity__SWIG_1(swigCPtr, this, Vec3d.getCPtr(ecc), ecc), true);
  }

}
