/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class BESOGroup {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public BESOGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BESOGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_BESOGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BESOGroup() {
    this(karambaJNI.new_BESOGroup(), true);
  }

  public void add(BESOElem elem) {
    karambaJNI.BESOGroup_add(swigCPtr, this, BESOElem.getCPtr(elem), elem);
  }

  public boolean isActive() {
    return karambaJNI.BESOGroup_isActive__SWIG_0(swigCPtr, this);
  }

  public boolean isActive(boolean isActive) {
    return karambaJNI.BESOGroup_isActive__SWIG_1(swigCPtr, this, isActive);
  }

  public boolean flipIsActive(int current_iteration) {
    return karambaJNI.BESOGroup_flipIsActive(swigCPtr, this, current_iteration);
  }

  public void updateWeight(VectInt lc, weightingInfo info) {
    karambaJNI.BESOGroup_updateWeight(swigCPtr, this, VectInt.getCPtr(lc), lc, weightingInfo.getCPtr(info), info);
  }

  public double weight() {
    return karambaJNI.BESOGroup_weight(swigCPtr, this);
  }

  public double mass() {
    return karambaJNI.BESOGroup_mass(swigCPtr, this);
  }

  public void init() {
    karambaJNI.BESOGroup_init(swigCPtr, this);
  }

  public void updateFEModel() {
    karambaJNI.BESOGroup_updateFEModel(swigCPtr, this);
  }

  public boolean neighborChanged(VectBool was_changed, SWIGTYPE_p_order__kdtree2 _kdtree, double _min_distance) {
    return karambaJNI.BESOGroup_neighborChanged(swigCPtr, this, VectBool.getCPtr(was_changed), was_changed, SWIGTYPE_p_order__kdtree2.getCPtr(_kdtree), _min_distance);
  }

  public void markAsChanged(VectBool was_changed) {
    karambaJNI.BESOGroup_markAsChanged(swigCPtr, this, VectBool.getCPtr(was_changed), was_changed);
  }

  public SWIGTYPE_p_std__vectorT_BESOElem_p_t members() {
    return new SWIGTYPE_p_std__vectorT_BESOElem_p_t(karambaJNI.BESOGroup_members(swigCPtr, this), false);
  }

}
