/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ESODesigner {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public ESODesigner(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ESODesigner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ESODesigner(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ESODesigner(Response response) {
    this(karambaJNI.new_ESODesigner(Response.getCPtr(response), response), true);
  }

  public void copy(ESODesigner orig) {
    karambaJNI.ESODesigner_copy(swigCPtr, this, ESODesigner.getCPtr(orig), orig);
  }

  public double optimize() {
    return karambaJNI.ESODesigner_optimize(swigCPtr, this);
  }

  public long maxDesignIter() {
    return karambaJNI.ESODesigner_maxDesignIter__SWIG_0(swigCPtr, this);
  }

  public long maxDesignIter(long max_iter) {
    return karambaJNI.ESODesigner_maxDesignIter__SWIG_1(swigCPtr, this, max_iter);
  }

  public double targetRemovalRatio() {
    return karambaJNI.ESODesigner_targetRemovalRatio__SWIG_0(swigCPtr, this);
  }

  public double targetRemovalRatio(double ratio) {
    return karambaJNI.ESODesigner_targetRemovalRatio__SWIG_1(swigCPtr, this, ratio);
  }

  public void add(Element element) {
    karambaJNI.ESODesigner_add(swigCPtr, this, Element.getCPtr(element), element);
  }

  public void inactiveMaterial(Material inactive_mat) {
    karambaJNI.ESODesigner_inactiveMaterial(swigCPtr, this, Material.getCPtr(inactive_mat), inactive_mat);
  }

}
