/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class UtilDetailsEC3 {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public UtilDetailsEC3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UtilDetailsEC3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_UtilDetailsEC3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void copy(UtilDetailsEC3 orig) {
    karambaJNI.UtilDetailsEC3_copy(swigCPtr, this, UtilDetailsEC3.getCPtr(orig), orig);
  }

  public void setBending_Y(UtilBendingBeam value) {
    karambaJNI.UtilDetailsEC3_bending_Y_set(swigCPtr, this, UtilBendingBeam.getCPtr(value), value);
  }

  public UtilBendingBeam getBending_Y() {
    long cPtr = karambaJNI.UtilDetailsEC3_bending_Y_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UtilBendingBeam(cPtr, false);
  }

  public void setBending_Z(UtilBendingBeam value) {
    karambaJNI.UtilDetailsEC3_bending_Z_set(swigCPtr, this, UtilBendingBeam.getCPtr(value), value);
  }

  public UtilBendingBeam getBending_Z() {
    long cPtr = karambaJNI.UtilDetailsEC3_bending_Z_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UtilBendingBeam(cPtr, false);
  }

  public void setShear(UtilShearBeam value) {
    karambaJNI.UtilDetailsEC3_shear_set(swigCPtr, this, UtilShearBeam.getCPtr(value), value);
  }

  public UtilShearBeam getShear() {
    long cPtr = karambaJNI.UtilDetailsEC3_shear_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UtilShearBeam(cPtr, false);
  }

  public double util() {
    return karambaJNI.UtilDetailsEC3_util(swigCPtr, this);
  }

  public UtilDetailsEC3() {
    this(karambaJNI.new_UtilDetailsEC3(), true);
  }

}
