/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class CroSecStateImp_Plastic_Beam_EC3 extends CroSecStateImp_LinearElastic_Beam_EC3 {
  private long swigCPtr;

  protected CroSecStateImp_Plastic_Beam_EC3(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.CroSecStateImp_Plastic_Beam_EC3_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CroSecStateImp_Plastic_Beam_EC3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_CroSecStateImp_Plastic_Beam_EC3(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CroSecStateImp_Plastic_Beam_EC3(double gamma_m0, double gamma_m1, double zg, double eps) {
    this(karambaJNI.new_CroSecStateImp_Plastic_Beam_EC3__SWIG_0(gamma_m0, gamma_m1, zg, eps), true);
  }

  public CroSecStateImp_Plastic_Beam_EC3(double gamma_m0, double gamma_m1, double zg) {
    this(karambaJNI.new_CroSecStateImp_Plastic_Beam_EC3__SWIG_1(gamma_m0, gamma_m1, zg), true);
  }

  public CroSecStateImp_Plastic_Beam_EC3(double gamma_m0, double gamma_m1) {
    this(karambaJNI.new_CroSecStateImp_Plastic_Beam_EC3__SWIG_2(gamma_m0, gamma_m1), true);
  }

  public CroSecStateImp_Plastic_Beam_EC3(double gamma_m0) {
    this(karambaJNI.new_CroSecStateImp_Plastic_Beam_EC3__SWIG_3(gamma_m0), true);
  }

  public CroSecStateImp_Plastic_Beam_EC3() {
    this(karambaJNI.new_CroSecStateImp_Plastic_Beam_EC3__SWIG_4(), true);
  }

  public CroSecStateImp clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.CroSecStateImp_Plastic_Beam_EC3_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new CroSecStateImp_Plastic_Beam_EC3(cPtr, false);
  }

  public CroSecStateImp clone() {
    long cPtr = karambaJNI.CroSecStateImp_Plastic_Beam_EC3_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new CroSecStateImp_Plastic_Beam_EC3(cPtr, false);
  }

}
