/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class BucklingLength {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public BucklingLength(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(BucklingLength obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_BucklingLength(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BucklingLength(Model model) {
    this(karambaJNI.new_BucklingLength__SWIG_1(Model.getCPtr(model), model), true);
  }

  public VectReal bklLengthZ() {
    return new VectReal(karambaJNI.BucklingLength_bklLengthZ__SWIG_0(swigCPtr, this), false);
  }

  public double bklLengthZ(long ind) {
    return karambaJNI.BucklingLength_bklLengthZ__SWIG_1(swigCPtr, this, ind);
  }

  public VectReal bklLengthY() {
    return new VectReal(karambaJNI.BucklingLength_bklLengthY__SWIG_0(swigCPtr, this), false);
  }

  public double bklLengthY(long ind) {
    return karambaJNI.BucklingLength_bklLengthY__SWIG_1(swigCPtr, this, ind);
  }

  public VectReal bklLengthLT() {
    return new VectReal(karambaJNI.BucklingLength_bklLengthLT__SWIG_0(swigCPtr, this), false);
  }

  public double bklLengthLT(long ind) {
    return karambaJNI.BucklingLength_bklLengthLT__SWIG_1(swigCPtr, this, ind);
  }

}
