/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class InitialStrain extends Load {
  private long swigCPtr;

  protected InitialStrain(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.InitialStrain_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InitialStrain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_InitialStrain(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public InitialStrain(double eps0) {
    this(karambaJNI.new_InitialStrain__SWIG_1(eps0), true);
  }

  public InitialStrain(InitialStrain arg) {
    this(karambaJNI.new_InitialStrain__SWIG_2(InitialStrain.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.InitialStrain_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new InitialStrain(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.InitialStrain_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new InitialStrain(cPtr, false);
  }

  public void copy(Load orig) {
    karambaJNI.InitialStrain_copy(swigCPtr, this, Load.getCPtr(orig), orig);
  }

  public void update(CooSys coosys) {
    karambaJNI.InitialStrain_update(swigCPtr, this, CooSys.getCPtr(coosys), coosys);
  }

  public double eps0() {
    return karambaJNI.InitialStrain_eps0(swigCPtr, this);
  }

}
