/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class UtilShearBeam {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public UtilShearBeam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UtilShearBeam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_UtilShearBeam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UtilShearBeam() {
    this(karambaJNI.new_UtilShearBeam(), true);
  }

  public void copy(UtilShearBeam orig) {
    karambaJNI.UtilShearBeam_copy(swigCPtr, this, UtilShearBeam.getCPtr(orig), orig);
  }

  public void setFac_Vy(double value) {
    karambaJNI.UtilShearBeam_fac_Vy_set(swigCPtr, this, value);
  }

  public double getFac_Vy() {
    return karambaJNI.UtilShearBeam_fac_Vy_get(swigCPtr, this);
  }

  public void setFac_Vz(double value) {
    karambaJNI.UtilShearBeam_fac_Vz_set(swigCPtr, this, value);
  }

  public double getFac_Vz() {
    return karambaJNI.UtilShearBeam_fac_Vz_get(swigCPtr, this);
  }

  public void setFac_Mt(double value) {
    karambaJNI.UtilShearBeam_fac_Mt_set(swigCPtr, this, value);
  }

  public double getFac_Mt() {
    return karambaJNI.UtilShearBeam_fac_Mt_get(swigCPtr, this);
  }

  public double util() {
    return karambaJNI.UtilShearBeam_util(swigCPtr, this);
  }

}
