/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class VectStrain {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public VectStrain(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectStrain obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_VectStrain(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectStrain() {
    this(karambaJNI.new_VectStrain__SWIG_0(), true);
  }

  public VectStrain(long n) {
    this(karambaJNI.new_VectStrain__SWIG_1(n), true);
  }

  public long size() {
    return karambaJNI.VectStrain_size(swigCPtr, this);
  }

  public long capacity() {
    return karambaJNI.VectStrain_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    karambaJNI.VectStrain_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return karambaJNI.VectStrain_isEmpty(swigCPtr, this);
  }

  public void clear() {
    karambaJNI.VectStrain_clear(swigCPtr, this);
  }

  public void add(CroSecStrain x) {
    karambaJNI.VectStrain_add(swigCPtr, this, CroSecStrain.getCPtr(x), x);
  }

  public CroSecStrain get(int i) {
    return new CroSecStrain(karambaJNI.VectStrain_get(swigCPtr, this, i), false);
  }

  public void set(int i, CroSecStrain val) {
    karambaJNI.VectStrain_set(swigCPtr, this, i, CroSecStrain.getCPtr(val), val);
  }

}
