/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Eigenform extends DeformThII {
  private long swigCPtr;

  protected Eigenform(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Eigenform_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Eigenform obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Eigenform(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Eigenform(Model model, int eigen_il, int eigen_iu, double eigen_fac) {
    this(karambaJNI.new_Eigenform__SWIG_1(Model.getCPtr(model), model, eigen_il, eigen_iu, eigen_fac), true);
  }

  public Eigenform(Model model, int eigen_il, int eigen_iu) {
    this(karambaJNI.new_Eigenform__SWIG_2(Model.getCPtr(model), model, eigen_il, eigen_iu), true);
  }

  public Eigenform(Model model, int eigen_il, int eigen_iu, int max_iter, double eps, int sign, double eigen_fac) {
    this(karambaJNI.new_Eigenform__SWIG_3(Model.getCPtr(model), model, eigen_il, eigen_iu, max_iter, eps, sign, eigen_fac), true);
  }

  public Eigenform(Eigenform arg) {
    this(karambaJNI.new_Eigenform__SWIG_4(Eigenform.getCPtr(arg), arg), true);
  }

  public Deform clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Eigenform_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Eigenform(cPtr, false);
  }

  public Deform clone() {
    long cPtr = karambaJNI.Eigenform_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Eigenform(cPtr, false);
  }

  public void copy(Deform orig) {
    karambaJNI.Eigenform_copy(swigCPtr, this, Deform.getCPtr(orig), orig);
  }

  public int analyze() {
    return karambaJNI.Eigenform_analyze(swigCPtr, this);
  }

  public VectReal eigenvalues() {
    return new VectReal(karambaJNI.Eigenform_eigenvalues(swigCPtr, this), true);
  }

}
