/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class CroSecStateVisitor_EC3 extends CroSecStateVisitor {
  private long swigCPtr;

  protected CroSecStateVisitor_EC3(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.CroSecStateVisitor_EC3_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CroSecStateVisitor_EC3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_CroSecStateVisitor_EC3(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CroSecStateVisitor_EC3() {
    this(karambaJNI.new_CroSecStateVisitor_EC3(), true);
  }

  public void setUtil(UtilDetailsEC3 value) {
    karambaJNI.CroSecStateVisitor_EC3_util_set(swigCPtr, this, UtilDetailsEC3.getCPtr(value), value);
  }

  public UtilDetailsEC3 getUtil() {
    long cPtr = karambaJNI.CroSecStateVisitor_EC3_util_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UtilDetailsEC3(cPtr, false);
  }

  public void setCalc(CalcDetailsEC3 value) {
    karambaJNI.CroSecStateVisitor_EC3_calc_set(swigCPtr, this, CalcDetailsEC3.getCPtr(value), value);
  }

  public CalcDetailsEC3 getCalc() {
    long cPtr = karambaJNI.CroSecStateVisitor_EC3_calc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CalcDetailsEC3(cPtr, false);
  }

  public void visit(SWIGTYPE_p_CroSecDesign__CroSecStateImp_LinearElastic_Beam_EC3_Simplified state) {
    karambaJNI.CroSecStateVisitor_EC3_visit__SWIG_0(swigCPtr, this, SWIGTYPE_p_CroSecDesign__CroSecStateImp_LinearElastic_Beam_EC3_Simplified.getCPtr(state));
  }

  public void visit(SWIGTYPE_p_CroSecDesign__CroSecStateImp_Plastic_Beam_EC3_Simplified state) {
    karambaJNI.CroSecStateVisitor_EC3_visit__SWIG_1(swigCPtr, this, SWIGTYPE_p_CroSecDesign__CroSecStateImp_Plastic_Beam_EC3_Simplified.getCPtr(state));
  }

  public void visit(CroSecStateImp_LinearElastic_Beam_EC3 state) {
    karambaJNI.CroSecStateVisitor_EC3_visit__SWIG_2(swigCPtr, this, CroSecStateImp_LinearElastic_Beam_EC3.getCPtr(state), state);
  }

  public void visit(CroSecStateImp_Plastic_Beam_EC3 state) {
    karambaJNI.CroSecStateVisitor_EC3_visit__SWIG_3(swigCPtr, this, CroSecStateImp_Plastic_Beam_EC3.getCPtr(state), state);
  }

  public void visit(CroSecStateImp_LinearElastic_Shell state) {
    karambaJNI.CroSecStateVisitor_EC3_visit__SWIG_4(swigCPtr, this, CroSecStateImp_LinearElastic_Shell.getCPtr(state), state);
  }

  public void visit(CroSecStateImp_Plastic_Shell state) {
    karambaJNI.CroSecStateVisitor_EC3_visit__SWIG_5(swigCPtr, this, CroSecStateImp_Plastic_Shell.getCPtr(state), state);
  }

}
