/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ElementVisitor {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public ElementVisitor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ElementVisitor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ElementVisitor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void visit(Model model) {
    karambaJNI.ElementVisitor_visit__SWIG_0(swigCPtr, this, Model.getCPtr(model), model);
  }

  public void visit(VectElem elems) {
    karambaJNI.ElementVisitor_visit__SWIG_1(swigCPtr, this, VectElem.getCPtr(elems), elems);
  }

  public void visit(Beam3D elem) {
    karambaJNI.ElementVisitor_visit__SWIG_2(swigCPtr, this, Beam3D.getCPtr(elem), elem);
  }

  public void visit(Truss3D elem) {
    karambaJNI.ElementVisitor_visit__SWIG_3(swigCPtr, this, Truss3D.getCPtr(elem), elem);
  }

  public void visit(Spring3D elem) {
    karambaJNI.ElementVisitor_visit__SWIG_4(swigCPtr, this, Spring3D.getCPtr(elem), elem);
  }

  public void visit(TriShell3D elem) {
    karambaJNI.ElementVisitor_visit__SWIG_5(swigCPtr, this, TriShell3D.getCPtr(elem), elem);
  }

}
