/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class VectBool {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public VectBool(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectBool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_VectBool(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectBool() {
    this(karambaJNI.new_VectBool__SWIG_0(), true);
  }

  public VectBool(long n) {
    this(karambaJNI.new_VectBool__SWIG_1(n), true);
  }

  public long size() {
    return karambaJNI.VectBool_size(swigCPtr, this);
  }

  public long capacity() {
    return karambaJNI.VectBool_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    karambaJNI.VectBool_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return karambaJNI.VectBool_isEmpty(swigCPtr, this);
  }

  public void clear() {
    karambaJNI.VectBool_clear(swigCPtr, this);
  }

  public void add(boolean x) {
    karambaJNI.VectBool_add(swigCPtr, this, x);
  }

  public boolean get(int i) {
    return karambaJNI.VectBool_get(swigCPtr, this, i);
  }

  public void set(int i, boolean val) {
    karambaJNI.VectBool_set(swigCPtr, this, i, val);
  }

}
