/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class UtilBendingBeam {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public UtilBendingBeam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(UtilBendingBeam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_UtilBendingBeam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UtilBendingBeam() {
    this(karambaJNI.new_UtilBendingBeam(), true);
  }

  public void copy(UtilBendingBeam orig) {
    karambaJNI.UtilBendingBeam_copy(swigCPtr, this, UtilBendingBeam.getCPtr(orig), orig);
  }

  public void setFac_N(double value) {
    karambaJNI.UtilBendingBeam_fac_N_set(swigCPtr, this, value);
  }

  public double getFac_N() {
    return karambaJNI.UtilBendingBeam_fac_N_get(swigCPtr, this);
  }

  public void setFac_My(double value) {
    karambaJNI.UtilBendingBeam_fac_My_set(swigCPtr, this, value);
  }

  public double getFac_My() {
    return karambaJNI.UtilBendingBeam_fac_My_get(swigCPtr, this);
  }

  public void setFac_Mz(double value) {
    karambaJNI.UtilBendingBeam_fac_Mz_set(swigCPtr, this, value);
  }

  public double getFac_Mz() {
    return karambaJNI.UtilBendingBeam_fac_Mz_get(swigCPtr, this);
  }

  public double util() {
    return karambaJNI.UtilBendingBeam_util(swigCPtr, this);
  }

}
