/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class VectElem {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public VectElem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectElem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_VectElem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectElem() {
    this(karambaJNI.new_VectElem__SWIG_0(), true);
  }

  public VectElem(long n) {
    this(karambaJNI.new_VectElem__SWIG_1(n), true);
  }

  public long size() {
    return karambaJNI.VectElem_size(swigCPtr, this);
  }

  public long capacity() {
    return karambaJNI.VectElem_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    karambaJNI.VectElem_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return karambaJNI.VectElem_isEmpty(swigCPtr, this);
  }

  public void clear() {
    karambaJNI.VectElem_clear(swigCPtr, this);
  }

  public void add(Element x) {
    karambaJNI.VectElem_add(swigCPtr, this, Element.getCPtr(x), x);
  }

  public Element get(int i) {
    long cPtr = karambaJNI.VectElem_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Element(cPtr, false);
  }

  public void set(int i, Element val) {
    karambaJNI.VectElem_set(swigCPtr, this, i, Element.getCPtr(val), val);
  }

}
