/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Beam3DCroSec_CHS extends Beam3DCroSec {
  private long swigCPtr;

  protected Beam3DCroSec_CHS(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Beam3DCroSec_CHS_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Beam3DCroSec_CHS obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Beam3DCroSec_CHS(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Beam3DCroSec_CHS() {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_0(), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt, double Ay_, double Az_, double Cw, double alpha_LT) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_1(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt, Ay_, Az_, Cw, alpha_LT), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt, double Ay_, double Az_, double Cw) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_2(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt, Ay_, Az_, Cw), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt, double Ay_, double Az_) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_3(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt, Ay_, Az_), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt, double Ay_) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_4(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt, Ay_), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_5(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_6(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_7(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_8(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_9(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_10(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_11(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_12(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_13(d, t, A, Iyy, Izz, Ipp, ky, kz, _group, Wely), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_14(d, t, A, Iyy, Izz, Ipp, ky, kz, _group), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky, double kz) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_15(d, t, A, Iyy, Izz, Ipp, ky, kz), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp, double ky) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_16(d, t, A, Iyy, Izz, Ipp, ky), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz, double Ipp) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_17(d, t, A, Iyy, Izz, Ipp), true);
  }

  public Beam3DCroSec_CHS(double d, double t, double A, double Iyy, double Izz) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_18(d, t, A, Iyy, Izz), true);
  }

  public Beam3DCroSec_CHS(Beam3DCroSec_CHS arg) {
    this(karambaJNI.new_Beam3DCroSec_CHS__SWIG_19(Beam3DCroSec_CHS.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Beam3DCroSec_CHS_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Beam3DCroSec_CHS(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.Beam3DCroSec_CHS_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Beam3DCroSec_CHS(cPtr, false);
  }

  public void copy(ElementCroSec orig) {
    karambaJNI.Beam3DCroSec_CHS_copy(swigCPtr, this, ElementCroSec.getCPtr(orig), orig);
  }

  public long croSecClass(double Ncompr, double My, double Mz, double eps) {
    return karambaJNI.Beam3DCroSec_CHS_croSecClass(swigCPtr, this, Ncompr, My, Mz, eps);
  }

  public boolean isHollow() {
    return karambaJNI.Beam3DCroSec_CHS_isHollow(swigCPtr, this);
  }

}
