/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class CooSys extends DeepCloneable {
  private long swigCPtr;

  protected CooSys(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.CooSys_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CooSys obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_CooSys(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CooSys() {
    this(karambaJNI.new_CooSys__SWIG_0(), true);
  }

  public CooSys(SWIGTYPE_p_Mat33 coosys) {
    this(karambaJNI.new_CooSys__SWIG_1(SWIGTYPE_p_Mat33.getCPtr(coosys)), true);
  }

  public CooSys(Vec3d v0, Vec3d v1) {
    this(karambaJNI.new_CooSys__SWIG_2(Vec3d.getCPtr(v0), v0, Vec3d.getCPtr(v1), v1), true);
  }

  public CooSys(Vec3d p0, Vec3d p1, Vec3d p2) {
    this(karambaJNI.new_CooSys__SWIG_3(Vec3d.getCPtr(p0), p0, Vec3d.getCPtr(p1), p1, Vec3d.getCPtr(p2), p2), true);
  }

  public CooSys(Vec3d x_axis, double theta) {
    this(karambaJNI.new_CooSys__SWIG_4(Vec3d.getCPtr(x_axis), x_axis, theta), true);
  }

  public CooSys(CooSys arg) {
    this(karambaJNI.new_CooSys__SWIG_5(CooSys.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.CooSys_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new CooSys(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.CooSys_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new CooSys(cPtr, false);
  }

  public void copy(CooSys orig) {
    karambaJNI.CooSys_copy(swigCPtr, this, CooSys.getCPtr(orig), orig);
  }

  public CooSys rotate(PointState state) {
    return new CooSys(karambaJNI.CooSys_rotate__SWIG_0(swigCPtr, this, PointState.getCPtr(state), state), true);
  }

  public CooSys rotate(Vec3d rot) {
    return new CooSys(karambaJNI.CooSys_rotate__SWIG_1(swigCPtr, this, Vec3d.getCPtr(rot), rot), true);
  }

  public Vec3d axis(long ind) {
    return new Vec3d(karambaJNI.CooSys_axis(swigCPtr, this, ind), true);
  }

  public SWIGTYPE_p_Mat33 t_l2g() {
    return new SWIGTYPE_p_Mat33(karambaJNI.CooSys_t_l2g__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_Mat33 t_l2g(PointState state) {
    return new SWIGTYPE_p_Mat33(karambaJNI.CooSys_t_l2g__SWIG_1(swigCPtr, this, PointState.getCPtr(state), state), true);
  }

  public SWIGTYPE_p_Mat33 t_g2l() {
    return new SWIGTYPE_p_Mat33(karambaJNI.CooSys_t_g2l(swigCPtr, this), true);
  }

  public VectReal axes() {
    return new VectReal(karambaJNI.CooSys_axes(swigCPtr, this), true);
  }

}
