/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class GeModel extends DeepCloneable {
  private long swigCPtr;

  protected GeModel(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.GeModel_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GeModel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_GeModel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GeModel(Model femodel) {
    this(karambaJNI.new_GeModel__SWIG_1(Model.getCPtr(femodel), femodel), true);
  }

  public GeModel(GeModel arg) {
    this(karambaJNI.new_GeModel__SWIG_2(GeModel.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.GeModel_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new GeModel(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.GeModel_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new GeModel(cPtr, false);
  }

  public void copy(GeModel orig) {
    karambaJNI.GeModel_copy(swigCPtr, this, GeModel.getCPtr(orig), orig);
  }

  public Model femodel() {
    long cPtr = karambaJNI.GeModel_femodel(swigCPtr, this);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

  public Model handOverFEModel() {
    long cPtr = karambaJNI.GeModel_handOverFEModel(swigCPtr, this);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

}
