/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class CalcDetailsEC3 {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public CalcDetailsEC3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CalcDetailsEC3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_CalcDetailsEC3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCrosec_class(long value) {
    karambaJNI.CalcDetailsEC3_crosec_class_set(swigCPtr, this, value);
  }

  public long getCrosec_class() {
    return karambaJNI.CalcDetailsEC3_crosec_class_get(swigCPtr, this);
  }

  public void setN_Rd(double value) {
    karambaJNI.CalcDetailsEC3_N_Rd_set(swigCPtr, this, value);
  }

  public double getN_Rd() {
    return karambaJNI.CalcDetailsEC3_N_Rd_get(swigCPtr, this);
  }

  public void setVy_Rd(double value) {
    karambaJNI.CalcDetailsEC3_Vy_Rd_set(swigCPtr, this, value);
  }

  public double getVy_Rd() {
    return karambaJNI.CalcDetailsEC3_Vy_Rd_get(swigCPtr, this);
  }

  public void setVz_Rd(double value) {
    karambaJNI.CalcDetailsEC3_Vz_Rd_set(swigCPtr, this, value);
  }

  public double getVz_Rd() {
    return karambaJNI.CalcDetailsEC3_Vz_Rd_get(swigCPtr, this);
  }

  public void setMt_Rd(double value) {
    karambaJNI.CalcDetailsEC3_Mt_Rd_set(swigCPtr, this, value);
  }

  public double getMt_Rd() {
    return karambaJNI.CalcDetailsEC3_Mt_Rd_get(swigCPtr, this);
  }

  public void setMy_Rd(double value) {
    karambaJNI.CalcDetailsEC3_My_Rd_set(swigCPtr, this, value);
  }

  public double getMy_Rd() {
    return karambaJNI.CalcDetailsEC3_My_Rd_get(swigCPtr, this);
  }

  public void setMz_Rd(double value) {
    karambaJNI.CalcDetailsEC3_Mz_Rd_set(swigCPtr, this, value);
  }

  public double getMz_Rd() {
    return karambaJNI.CalcDetailsEC3_Mz_Rd_get(swigCPtr, this);
  }

  public void setMcr(double value) {
    karambaJNI.CalcDetailsEC3_Mcr_set(swigCPtr, this, value);
  }

  public double getMcr() {
    return karambaJNI.CalcDetailsEC3_Mcr_get(swigCPtr, this);
  }

  public void setNcr_y(double value) {
    karambaJNI.CalcDetailsEC3_Ncr_y_set(swigCPtr, this, value);
  }

  public double getNcr_y() {
    return karambaJNI.CalcDetailsEC3_Ncr_y_get(swigCPtr, this);
  }

  public void setNcr_z(double value) {
    karambaJNI.CalcDetailsEC3_Ncr_z_set(swigCPtr, this, value);
  }

  public double getNcr_z() {
    return karambaJNI.CalcDetailsEC3_Ncr_z_get(swigCPtr, this);
  }

  public void setPsi_y(double value) {
    karambaJNI.CalcDetailsEC3_psi_y_set(swigCPtr, this, value);
  }

  public double getPsi_y() {
    return karambaJNI.CalcDetailsEC3_psi_y_get(swigCPtr, this);
  }

  public void setCmy(double value) {
    karambaJNI.CalcDetailsEC3_Cmy_set(swigCPtr, this, value);
  }

  public double getCmy() {
    return karambaJNI.CalcDetailsEC3_Cmy_get(swigCPtr, this);
  }

  public void setCmz(double value) {
    karambaJNI.CalcDetailsEC3_Cmz_set(swigCPtr, this, value);
  }

  public double getCmz() {
    return karambaJNI.CalcDetailsEC3_Cmz_get(swigCPtr, this);
  }

  public void setCmLT(double value) {
    karambaJNI.CalcDetailsEC3_CmLT_set(swigCPtr, this, value);
  }

  public double getCmLT() {
    return karambaJNI.CalcDetailsEC3_CmLT_get(swigCPtr, this);
  }

  public void setChi_y(double value) {
    karambaJNI.CalcDetailsEC3_chi_y_set(swigCPtr, this, value);
  }

  public double getChi_y() {
    return karambaJNI.CalcDetailsEC3_chi_y_get(swigCPtr, this);
  }

  public void setChi_z(double value) {
    karambaJNI.CalcDetailsEC3_chi_z_set(swigCPtr, this, value);
  }

  public double getChi_z() {
    return karambaJNI.CalcDetailsEC3_chi_z_get(swigCPtr, this);
  }

  public void setChi_LT_mod(double value) {
    karambaJNI.CalcDetailsEC3_chi_LT_mod_set(swigCPtr, this, value);
  }

  public double getChi_LT_mod() {
    return karambaJNI.CalcDetailsEC3_chi_LT_mod_get(swigCPtr, this);
  }

  public void setKyy(double value) {
    karambaJNI.CalcDetailsEC3_kyy_set(swigCPtr, this, value);
  }

  public double getKyy() {
    return karambaJNI.CalcDetailsEC3_kyy_get(swigCPtr, this);
  }

  public void setKzz(double value) {
    karambaJNI.CalcDetailsEC3_kzz_set(swigCPtr, this, value);
  }

  public double getKzz() {
    return karambaJNI.CalcDetailsEC3_kzz_get(swigCPtr, this);
  }

  public void setKyz(double value) {
    karambaJNI.CalcDetailsEC3_kyz_set(swigCPtr, this, value);
  }

  public double getKyz() {
    return karambaJNI.CalcDetailsEC3_kyz_get(swigCPtr, this);
  }

  public void setKzy(double value) {
    karambaJNI.CalcDetailsEC3_kzy_set(swigCPtr, this, value);
  }

  public double getKzy() {
    return karambaJNI.CalcDetailsEC3_kzy_get(swigCPtr, this);
  }

  public CalcDetailsEC3() {
    this(karambaJNI.new_CalcDetailsEC3(), true);
  }

}
