/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ConstantElementDirectionStrategy extends ElementDirectionStrategy {
  private long swigCPtr;

  protected ConstantElementDirectionStrategy(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.ConstantElementDirectionStrategy_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConstantElementDirectionStrategy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ConstantElementDirectionStrategy(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ConstantElementDirectionStrategy(Vec3d dir) {
    this(karambaJNI.new_ConstantElementDirectionStrategy(Vec3d.getCPtr(dir), dir), true);
  }

  public Vec3d elementDir(long i) {
    return new Vec3d(karambaJNI.ConstantElementDirectionStrategy_elementDir(swigCPtr, this, i), false);
  }

}
