/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ElementStraightLineState extends ElementState {
  private long swigCPtr;

  protected ElementStraightLineState(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.ElementStraightLineState_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ElementStraightLineState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ElementStraightLineState(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void copy(ElementState orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    karambaJNI.ElementStraightLineState_copy__SWIG_0(swigCPtr, this, ElementState.getCPtr(orig), orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
  }

  public void copy(ElementState orig) {
    karambaJNI.ElementStraightLineState_copy__SWIG_1(swigCPtr, this, ElementState.getCPtr(orig), orig);
  }

  public SWIGTYPE_p_VecReal globalForce(long lc, long ind) {
    return new SWIGTYPE_p_VecReal(karambaJNI.ElementStraightLineState_globalForce(swigCPtr, this, lc, ind), true);
  }

  public void updateDisplacements(long lc, long ind, SWIGTYPE_p_VecReal global_disp) {
    karambaJNI.ElementStraightLineState_updateDisplacements(swigCPtr, this, lc, ind, SWIGTYPE_p_VecReal.getCPtr(global_disp));
  }

  public void setEccentricity(SWIGTYPE_p_MatReal T_c2e) {
    karambaJNI.ElementStraightLineState_setEccentricity(swigCPtr, this, SWIGTYPE_p_MatReal.getCPtr(T_c2e));
  }

}
