/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Surface3DSigEps {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public Surface3DSigEps(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Surface3DSigEps obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Surface3DSigEps(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Surface3DSigEps() {
    this(karambaJNI.new_Surface3DSigEps__SWIG_0(), true);
  }

  public Surface3DSigEps(Vec3d eps, Material material) {
    this(karambaJNI.new_Surface3DSigEps__SWIG_1(Vec3d.getCPtr(eps), eps, Material.getCPtr(material), material), true);
  }

  public Surface3DSigEps clone() {
    long cPtr = karambaJNI.Surface3DSigEps_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Surface3DSigEps(cPtr, false);
  }

  public void copy(Surface3DSigEps orig) {
    karambaJNI.Surface3DSigEps_copy(swigCPtr, this, Surface3DSigEps.getCPtr(orig), orig);
  }

  public Vec3d eps() {
    return new Vec3d(karambaJNI.Surface3DSigEps_eps(swigCPtr, this), true);
  }

  public Vec3d sig() {
    return new Vec3d(karambaJNI.Surface3DSigEps_sig(swigCPtr, this), true);
  }

  public Vec3d eps_princ() {
    return new Vec3d(karambaJNI.Surface3DSigEps_eps_princ(swigCPtr, this), true);
  }

  public Vec3d sig_princ() {
    return new Vec3d(karambaJNI.Surface3DSigEps_sig_princ(swigCPtr, this), true);
  }

  public double sig_vonMises() {
    return karambaJNI.Surface3DSigEps_sig_vonMises(swigCPtr, this);
  }

  public double sig_vonMises_signed() {
    return karambaJNI.Surface3DSigEps_sig_vonMises_signed(swigCPtr, this);
  }

  public double utilization() {
    return karambaJNI.Surface3DSigEps_utilization(swigCPtr, this);
  }

  public double utilization_signed() {
    return karambaJNI.Surface3DSigEps_utilization_signed(swigCPtr, this);
  }

  public Vec3d vecResult(SurfaceResultTag res_tag) {
    return new Vec3d(karambaJNI.Surface3DSigEps_vecResult(swigCPtr, this, res_tag.swigValue()), true);
  }

  public double scalResult(SurfaceResultTag res_tag) {
    return karambaJNI.Surface3DSigEps_scalResult(swigCPtr, this, res_tag.swigValue());
  }

  public void add(Surface3DSigEps other) {
    karambaJNI.Surface3DSigEps_add(swigCPtr, this, Surface3DSigEps.getCPtr(other), other);
  }

  public void scale(double fac) {
    karambaJNI.Surface3DSigEps_scale(swigCPtr, this, fac);
  }

  public SWIGTYPE_p_tvmet__VectorT_real_2_t transformSigTo(SWIGTYPE_p_tvmet__VectorT_real_2_t dir) {
    return new SWIGTYPE_p_tvmet__VectorT_real_2_t(karambaJNI.Surface3DSigEps_transformSigTo(swigCPtr, this, SWIGTYPE_p_tvmet__VectorT_real_2_t.getCPtr(dir)), true);
  }

}
