/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class VectFlowPathPos {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public VectFlowPathPos(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectFlowPathPos obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_VectFlowPathPos(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectFlowPathPos() {
    this(karambaJNI.new_VectFlowPathPos__SWIG_0(), true);
  }

  public VectFlowPathPos(long n) {
    this(karambaJNI.new_VectFlowPathPos__SWIG_1(n), true);
  }

  public long size() {
    return karambaJNI.VectFlowPathPos_size(swigCPtr, this);
  }

  public long capacity() {
    return karambaJNI.VectFlowPathPos_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    karambaJNI.VectFlowPathPos_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return karambaJNI.VectFlowPathPos_isEmpty(swigCPtr, this);
  }

  public void clear() {
    karambaJNI.VectFlowPathPos_clear(swigCPtr, this);
  }

  public void add(FlowPathPos x) {
    karambaJNI.VectFlowPathPos_add(swigCPtr, this, FlowPathPos.getCPtr(x), x);
  }

  public FlowPathPos get(int i) {
    return new FlowPathPos(karambaJNI.VectFlowPathPos_get(swigCPtr, this, i), false);
  }

  public void set(int i, FlowPathPos val) {
    karambaJNI.VectFlowPathPos_set(swigCPtr, this, i, FlowPathPos.getCPtr(val), val);
  }

}
