/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class CroSecStateImp {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public CroSecStateImp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(CroSecStateImp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_CroSecStateImp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CroSecStateImp clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.CroSecStateImp_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new CroSecStateImp(cPtr, false);
  }

  public CroSecStateImp clone() {
    long cPtr = karambaJNI.CroSecStateImp_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new CroSecStateImp(cPtr, false);
  }

  public double utilization(Element elem, ActionVisitor action, BucklingLength bkl_len, ElementCroSec crosec, boolean can_buckle) {
    return karambaJNI.CroSecStateImp_utilization(swigCPtr, this, Element.getCPtr(elem), elem, ActionVisitor.getCPtr(action), action, BucklingLength.getCPtr(bkl_len), bkl_len, ElementCroSec.getCPtr(crosec), crosec, can_buckle);
  }

  public void accept(CroSecStateVisitor visitor) {
    karambaJNI.CroSecStateImp_accept(swigCPtr, this, CroSecStateVisitor.getCPtr(visitor), visitor);
  }

}
