/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class KDTreeMultiDim {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public KDTreeMultiDim(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(KDTreeMultiDim obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_KDTreeMultiDim(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public KDTreeMultiDim() {
    this(karambaJNI.new_KDTreeMultiDim(), true);
  }

  public void insert(VectReal point) {
    karambaJNI.KDTreeMultiDim_insert(swigCPtr, this, VectReal.getCPtr(point), point);
  }

  public VectInt nNearest(VectReal point, int n) {
    return new VectInt(karambaJNI.KDTreeMultiDim_nNearest(swigCPtr, this, VectReal.getCPtr(point), point, n), true);
  }

  public void order() {
    karambaJNI.KDTreeMultiDim_order(swigCPtr, this);
  }

}
