/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Response {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public Response(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Response obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Response(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Response(Deform analysis) {
    this(karambaJNI.new_Response__SWIG_1(Deform.getCPtr(analysis), analysis), true);
  }

  public Response(Response arg) {
    this(karambaJNI.new_Response__SWIG_2(Response.getCPtr(arg), arg), true);
  }

  public Response clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Response_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Response(cPtr, false);
  }

  public Response clone() {
    long cPtr = karambaJNI.Response_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Response(cPtr, false);
  }

  public void copy(Response orig) {
    karambaJNI.Response_copy(swigCPtr, this, Response.getCPtr(orig), orig);
  }

  public Deform analysis() {
    long cPtr = karambaJNI.Response_analysis(swigCPtr, this);
    return (cPtr == 0) ? null : new Deform(cPtr, false);
  }

  public Model model() {
    long cPtr = karambaJNI.Response_model(swigCPtr, this);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

  public double maxLCBendingEnergy() {
    return karambaJNI.Response_maxLCBendingEnergy(swigCPtr, this);
  }

  public double bendingEnergy(int lc) {
    return karambaJNI.Response_bendingEnergy__SWIG_0(swigCPtr, this, lc);
  }

  public double bendingEnergy() {
    return karambaJNI.Response_bendingEnergy__SWIG_1(swigCPtr, this);
  }

  public double compliance(int lc) {
    return karambaJNI.Response_compliance(swigCPtr, this, lc);
  }

  public double maxLCCompliance() {
    return karambaJNI.Response_maxLCCompliance(swigCPtr, this);
  }

  public double maxLCWeightedCompressionCompliance() {
    return karambaJNI.Response_maxLCWeightedCompressionCompliance(swigCPtr, this);
  }

  public double weightedCompressionCompliance(int lc) {
    return karambaJNI.Response_weightedCompressionCompliance(swigCPtr, this, lc);
  }

  public double maxNodalDisplacement() {
    return karambaJNI.Response_maxNodalDisplacement__SWIG_0(swigCPtr, this);
  }

  public double maxNodalDisplacement(int lc) {
    return karambaJNI.Response_maxNodalDisplacement__SWIG_1(swigCPtr, this, lc);
  }

  public double maxDisplacement() {
    return karambaJNI.Response_maxDisplacement__SWIG_0(swigCPtr, this);
  }

  public double maxDisplacement(int lc) {
    return karambaJNI.Response_maxDisplacement__SWIG_1(swigCPtr, this, lc);
  }

  public double deadWeight(long lc) {
    return karambaJNI.Response_deadWeight(swigCPtr, this, lc);
  }

  public int updateMemberForces() {
    return karambaJNI.Response_updateMemberForces(swigCPtr, this);
  }

  public int updateNodalDisplacements() {
    return karambaJNI.Response_updateNodalDisplacements(swigCPtr, this);
  }

  public void touch() {
    karambaJNI.Response_touch(swigCPtr, this);
  }

}
