/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class TriShell3dLoadInfo extends TriFaceInfo {
  private long swigCPtr;

  protected TriShell3dLoadInfo(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.TriShell3dLoadInfo_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TriShell3dLoadInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_TriShell3dLoadInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setKapa_ct(SWIGTYPE_p_VecReal value) {
    karambaJNI.TriShell3dLoadInfo_kapa_ct_set(swigCPtr, this, SWIGTYPE_p_VecReal.getCPtr(value));
  }

  public SWIGTYPE_p_VecReal getKapa_ct() {
    return new SWIGTYPE_p_VecReal(karambaJNI.TriShell3dLoadInfo_kapa_ct_get(swigCPtr, this), true);
  }

  public TriShell3dLoadInfo() {
    this(karambaJNI.new_TriShell3dLoadInfo(), true);
  }

}
