/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Truss3DLoadInfo extends ElementStraightLineLoadInfo {
  private long swigCPtr;

  protected Truss3DLoadInfo(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Truss3DLoadInfo_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Truss3DLoadInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Truss3DLoadInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Truss3DLoadInfo(double length, double nII) {
    this(karambaJNI.new_Truss3DLoadInfo(length, nII), true);
  }

  public VectReal aj() {
    return new VectReal(karambaJNI.Truss3DLoadInfo_aj(swigCPtr, this), false);
  }

  public VectReal bjy() {
    return new VectReal(karambaJNI.Truss3DLoadInfo_bjy(swigCPtr, this), false);
  }

  public VectReal bjz() {
    return new VectReal(karambaJNI.Truss3DLoadInfo_bjz(swigCPtr, this), false);
  }

  public double ky() {
    return karambaJNI.Truss3DLoadInfo_ky(swigCPtr, this);
  }

  public double kz() {
    return karambaJNI.Truss3DLoadInfo_kz(swigCPtr, this);
  }

  public double gammay() {
    return karambaJNI.Truss3DLoadInfo_gammay(swigCPtr, this);
  }

  public double gammaz() {
    return karambaJNI.Truss3DLoadInfo_gammaz(swigCPtr, this);
  }

  public double nII() {
    return karambaJNI.Truss3DLoadInfo_nII(swigCPtr, this);
  }

  public void setPos(double pos) {
    karambaJNI.Truss3DLoadInfo_setPos(swigCPtr, this, pos);
  }

  public double length() {
    return karambaJNI.Truss3DLoadInfo_length(swigCPtr, this);
  }

  public double invEIy() {
    return karambaJNI.Truss3DLoadInfo_invEIy(swigCPtr, this);
  }

  public double invGAz() {
    return karambaJNI.Truss3DLoadInfo_invGAz(swigCPtr, this);
  }

  public double invEIz() {
    return karambaJNI.Truss3DLoadInfo_invEIz(swigCPtr, this);
  }

  public double invGAy() {
    return karambaJNI.Truss3DLoadInfo_invGAy(swigCPtr, this);
  }

}
