/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Deform {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public Deform(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Deform obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Deform(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Deform(Model model) {
    this(karambaJNI.new_Deform__SWIG_1(Model.getCPtr(model), model), true);
  }

  public Deform(Deform arg) {
    this(karambaJNI.new_Deform__SWIG_2(Deform.getCPtr(arg), arg), true);
  }

  public Deform clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Deform_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Deform(cPtr, false);
  }

  public Deform clone() {
    long cPtr = karambaJNI.Deform_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Deform(cPtr, false);
  }

  public void copy(Deform orig) {
    karambaJNI.Deform_copy(swigCPtr, this, Deform.getCPtr(orig), orig);
  }

  public Model model() {
    long cPtr = karambaJNI.Deform_model(swigCPtr, this);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

  public int analyze() {
    return karambaJNI.Deform_analyze(swigCPtr, this);
  }

  public double compliance(long lc) {
    return karambaJNI.Deform_compliance(swigCPtr, this, lc);
  }

  public double deadWeight(long lc) {
    return karambaJNI.Deform_deadWeight(swigCPtr, this, lc);
  }

  public void touch() {
    karambaJNI.Deform_touch(swigCPtr, this);
  }

  public long stiffness_bandwidth() {
    return karambaJNI.Deform_stiffness_bandwidth(swigCPtr, this);
  }

  public long stiffness_numequ() {
    return karambaJNI.Deform_stiffness_numequ(swigCPtr, this);
  }

}
