/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ShellMesh extends DeepCloneable {
  private long swigCPtr;

  protected ShellMesh(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.ShellMesh_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ShellMesh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ShellMesh(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ShellMesh() {
    this(karambaJNI.new_ShellMesh__SWIG_0(), true);
  }

  public ShellMesh(ShellMesh arg, SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    this(karambaJNI.new_ShellMesh__SWIG_1(ShellMesh.getCPtr(arg), arg, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict)), true);
  }

  public ShellMesh(ShellMesh arg) {
    this(karambaJNI.new_ShellMesh__SWIG_2(ShellMesh.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.ShellMesh_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new ShellMesh(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.ShellMesh_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new ShellMesh(cPtr, false);
  }

  public void copy(ShellMesh orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    karambaJNI.ShellMesh_copy__SWIG_0(swigCPtr, this, ShellMesh.getCPtr(orig), orig, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
  }

  public void copy(ShellMesh orig) {
    karambaJNI.ShellMesh_copy__SWIG_1(swigCPtr, this, ShellMesh.getCPtr(orig), orig);
  }

  public long add(TriShell3D elem) {
    return karambaJNI.ShellMesh_add__SWIG_0(swigCPtr, this, TriShell3D.getCPtr(elem), elem);
  }

  public long add(ShellMesh mesh) {
    return karambaJNI.ShellMesh_add__SWIG_1(swigCPtr, this, ShellMesh.getCPtr(mesh), mesh);
  }

  public void finalizeConstruction() {
    karambaJNI.ShellMesh_finalizeConstruction(swigCPtr, this);
  }

  public Mesh mesh() {
    return new Mesh(karambaJNI.ShellMesh_mesh__SWIG_0(swigCPtr, this), false);
  }

  public int meshInd(Vertex vert) {
    return karambaJNI.ShellMesh_meshInd__SWIG_0(swigCPtr, this, Vertex.getCPtr(vert), vert);
  }

  public int meshInd(long vert_id) {
    return karambaJNI.ShellMesh_meshInd__SWIG_1(swigCPtr, this, vert_id);
  }

  public SWIGTYPE_p_VecIndexes facesOfEdge(long n1, long n2) {
    return new SWIGTYPE_p_VecIndexes(karambaJNI.ShellMesh_facesOfEdge(swigCPtr, this, n1, n2), true);
  }

  public SWIGTYPE_p_VecIndexes facesOfVertex(long vertex_index) {
    return new SWIGTYPE_p_VecIndexes(karambaJNI.ShellMesh_facesOfVertex(swigCPtr, this, vertex_index), false);
  }

  public long numberOfElems() {
    return karambaJNI.ShellMesh_numberOfElems(swigCPtr, this);
  }

  public TriShell3D elem(long ind) {
    long cPtr = karambaJNI.ShellMesh_elem__SWIG_0(swigCPtr, this, ind);
    return (cPtr == 0) ? null : new TriShell3D(cPtr, false);
  }

  public VectTriShell3D elems() {
    return new VectTriShell3D(karambaJNI.ShellMesh_elems__SWIG_0(swigCPtr, this), false);
  }

  public SWIGTYPE_p_VecIndexes vertexIndexesOfFace(long ind) {
    return new SWIGTYPE_p_VecIndexes(karambaJNI.ShellMesh_vertexIndexesOfFace(swigCPtr, this, ind), true);
  }

  public long numberOfVertexes() {
    return karambaJNI.ShellMesh_numberOfVertexes(swigCPtr, this);
  }

  public Vertex vertex(long ind) {
    long cPtr = karambaJNI.ShellMesh_vertex__SWIG_0(swigCPtr, this, ind);
    return (cPtr == 0) ? null : new Vertex(cPtr, false);
  }

  public Material material(Material mat) {
    return new Material(karambaJNI.ShellMesh_material(swigCPtr, this, Material.getCPtr(mat), mat), false);
  }

  public VectReal elementScalarResult(SurfaceResultTag tag, double z, long lc, double fac) {
    return new VectReal(karambaJNI.ShellMesh_elementScalarResult(swigCPtr, this, tag.swigValue(), z, lc, fac), true);
  }

  public VectVec3d elementPrincipalResult(Surface3DVecEvalStrategy eval_strat, double fac) {
    return new VectVec3d(karambaJNI.ShellMesh_elementPrincipalResult__SWIG_0(swigCPtr, this, Surface3DVecEvalStrategy.getCPtr(eval_strat), eval_strat, fac), true);
  }

  public VectVec3d elementPrincipalResult(Surface3DVecEvalStrategy eval_strat, VectReal lc_fac) {
    return new VectVec3d(karambaJNI.ShellMesh_elementPrincipalResult__SWIG_1(swigCPtr, this, Surface3DVecEvalStrategy.getCPtr(eval_strat), eval_strat, VectReal.getCPtr(lc_fac), lc_fac), true);
  }

  public VectVec3d elementVectorResult(SurfaceResultTag tag, double z_rel, VectReal lc_fac) {
    return new VectVec3d(karambaJNI.ShellMesh_elementVectorResult__SWIG_0(swigCPtr, this, tag.swigValue(), z_rel, VectReal.getCPtr(lc_fac), lc_fac), true);
  }

  public VectVec3d elementVectorResult(SurfaceResultTag tag, double z_rel, long lc, double fac) {
    return new VectVec3d(karambaJNI.ShellMesh_elementVectorResult__SWIG_1(swigCPtr, this, tag.swigValue(), z_rel, lc, fac), true);
  }

  public VectSurface3DSigEps elementSigEps(double z_rel, long lc, double fac) {
    return new VectSurface3DSigEps(karambaJNI.ShellMesh_elementSigEps__SWIG_0(swigCPtr, this, z_rel, lc, fac), true);
  }

  public VectSurface3DSigEps elementSigEps(double z_rel, VectReal lc_fac) {
    return new VectSurface3DSigEps(karambaJNI.ShellMesh_elementSigEps__SWIG_1(swigCPtr, this, z_rel, VectReal.getCPtr(lc_fac), lc_fac), true);
  }

  public VectSurface3DResultants elementResultants(long lc, double fac) {
    return new VectSurface3DResultants(karambaJNI.ShellMesh_elementResultants__SWIG_0(swigCPtr, this, lc, fac), true);
  }

  public VectSurface3DResultants elementResultants(VectReal lc_fac) {
    return new VectSurface3DResultants(karambaJNI.ShellMesh_elementResultants__SWIG_1(swigCPtr, this, VectReal.getCPtr(lc_fac), lc_fac), true);
  }

  public VectVec3d nodalVectorResult(SurfaceResultTag tag, VectReal lc_fac) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalVectorResult(swigCPtr, this, tag.swigValue(), VectReal.getCPtr(lc_fac), lc_fac), true);
  }

  public VectReal nodalScalarResult(SurfaceResultTag tag, double z_rel, long lc, double fac) {
    return new VectReal(karambaJNI.ShellMesh_nodalScalarResult__SWIG_0(swigCPtr, this, tag.swigValue(), z_rel, lc, fac), true);
  }

  public VectReal nodalScalarResult(SurfaceResultTag tag, double z_rel, VectReal lc_fac) {
    return new VectReal(karambaJNI.ShellMesh_nodalScalarResult__SWIG_1(swigCPtr, this, tag.swigValue(), z_rel, VectReal.getCPtr(lc_fac), lc_fac), true);
  }

  public VectVec3d nodalPrincipalResult(Surface3DVecEvalStrategy eval_strat, double fac) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalPrincipalResult__SWIG_0(swigCPtr, this, Surface3DVecEvalStrategy.getCPtr(eval_strat), eval_strat, fac), true);
  }

  public VectVec3d nodalPrincipalResult(Surface3DVecEvalStrategy eval_strat, VectReal lc_fac) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalPrincipalResult__SWIG_1(swigCPtr, this, Surface3DVecEvalStrategy.getCPtr(eval_strat), eval_strat, VectReal.getCPtr(lc_fac), lc_fac), true);
  }

  public VectVec3d nodalFlowDirResult(Vec3d flow_dir, double z_rel, long lc, double fac, double theta) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalFlowDirResult__SWIG_0(swigCPtr, this, Vec3d.getCPtr(flow_dir), flow_dir, z_rel, lc, fac, theta), true);
  }

  public VectVec3d nodalFlowDirResult(Vec3d flow_dir, double z_rel, long lc, double fac) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalFlowDirResult__SWIG_1(swigCPtr, this, Vec3d.getCPtr(flow_dir), flow_dir, z_rel, lc, fac), true);
  }

  public VectVec3d nodalFlowDirResult(Vec3d flow_dir, double z_rel, VectReal lc_fac, double theta) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalFlowDirResult__SWIG_2(swigCPtr, this, Vec3d.getCPtr(flow_dir), flow_dir, z_rel, VectReal.getCPtr(lc_fac), lc_fac, theta), true);
  }

  public VectVec3d nodalFlowDirResult(Vec3d flow_dir, double z_rel, VectReal lc_fac) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalFlowDirResult__SWIG_3(swigCPtr, this, Vec3d.getCPtr(flow_dir), flow_dir, z_rel, VectReal.getCPtr(lc_fac), lc_fac), true);
  }

  public VectVec3d nodalFlowDirResult(VectVec3d flow_dirs, VectVec3d flow_dirs_pos, double z_rel, long lc, double fac, double theta) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalFlowDirResult__SWIG_4(swigCPtr, this, VectVec3d.getCPtr(flow_dirs), flow_dirs, VectVec3d.getCPtr(flow_dirs_pos), flow_dirs_pos, z_rel, lc, fac, theta), true);
  }

  public VectVec3d nodalFlowDirResult(VectVec3d flow_dirs, VectVec3d flow_dirs_pos, double z_rel, long lc, double fac) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalFlowDirResult__SWIG_5(swigCPtr, this, VectVec3d.getCPtr(flow_dirs), flow_dirs, VectVec3d.getCPtr(flow_dirs_pos), flow_dirs_pos, z_rel, lc, fac), true);
  }

  public VectVec3d nodalFlowDirResult(VectVec3d flow_dirs, VectVec3d flow_dirs_pos, double z_rel, VectReal lc_fac, double theta) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalFlowDirResult__SWIG_6(swigCPtr, this, VectVec3d.getCPtr(flow_dirs), flow_dirs, VectVec3d.getCPtr(flow_dirs_pos), flow_dirs_pos, z_rel, VectReal.getCPtr(lc_fac), lc_fac, theta), true);
  }

  public VectVec3d nodalFlowDirResult(VectVec3d flow_dirs, VectVec3d flow_dirs_pos, double z_rel, VectReal lc_fac) {
    return new VectVec3d(karambaJNI.ShellMesh_nodalFlowDirResult__SWIG_7(swigCPtr, this, VectVec3d.getCPtr(flow_dirs), flow_dirs, VectVec3d.getCPtr(flow_dirs_pos), flow_dirs_pos, z_rel, VectReal.getCPtr(lc_fac), lc_fac), true);
  }

  public double axialDeformationEnergy(int lc) {
    return karambaJNI.ShellMesh_axialDeformationEnergy__SWIG_0(swigCPtr, this, lc);
  }

  public double axialDeformationEnergy() {
    return karambaJNI.ShellMesh_axialDeformationEnergy__SWIG_1(swigCPtr, this);
  }

  public double bendingEnergy(int lc) {
    return karambaJNI.ShellMesh_bendingEnergy__SWIG_0(swigCPtr, this, lc);
  }

  public double bendingEnergy() {
    return karambaJNI.ShellMesh_bendingEnergy__SWIG_1(swigCPtr, this);
  }

}
