/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ElementStraightLineLoadInfo {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public ElementStraightLineLoadInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ElementStraightLineLoadInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ElementStraightLineLoadInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectReal aj() {
    return new VectReal(karambaJNI.ElementStraightLineLoadInfo_aj(swigCPtr, this), false);
  }

  public VectReal bjy() {
    return new VectReal(karambaJNI.ElementStraightLineLoadInfo_bjy(swigCPtr, this), false);
  }

  public VectReal bjz() {
    return new VectReal(karambaJNI.ElementStraightLineLoadInfo_bjz(swigCPtr, this), false);
  }

  public double ky() {
    return karambaJNI.ElementStraightLineLoadInfo_ky(swigCPtr, this);
  }

  public double kz() {
    return karambaJNI.ElementStraightLineLoadInfo_kz(swigCPtr, this);
  }

  public double gammay() {
    return karambaJNI.ElementStraightLineLoadInfo_gammay(swigCPtr, this);
  }

  public double gammaz() {
    return karambaJNI.ElementStraightLineLoadInfo_gammaz(swigCPtr, this);
  }

  public double nII() {
    return karambaJNI.ElementStraightLineLoadInfo_nII(swigCPtr, this);
  }

  public void setPos(double pos) {
    karambaJNI.ElementStraightLineLoadInfo_setPos(swigCPtr, this, pos);
  }

  public double length() {
    return karambaJNI.ElementStraightLineLoadInfo_length(swigCPtr, this);
  }

  public double invEIy() {
    return karambaJNI.ElementStraightLineLoadInfo_invEIy(swigCPtr, this);
  }

  public double invGAz() {
    return karambaJNI.ElementStraightLineLoadInfo_invGAz(swigCPtr, this);
  }

  public double invEIz() {
    return karambaJNI.ElementStraightLineLoadInfo_invEIz(swigCPtr, this);
  }

  public double invGAy() {
    return karambaJNI.ElementStraightLineLoadInfo_invGAy(swigCPtr, this);
  }

  public void addPsi0(Vec3d psi0) {
    karambaJNI.ElementStraightLineLoadInfo_addPsi0(swigCPtr, this, Vec3d.getCPtr(psi0), psi0);
  }

  public Vec3d psi0() {
    return new Vec3d(karambaJNI.ElementStraightLineLoadInfo_psi0(swigCPtr, this), false);
  }

  public final static long maxDegAj = karambaJNI.ElementStraightLineLoadInfo_maxDegAj_get();
}
