/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class NaturalVibe extends Eigenform {
  private long swigCPtr;

  protected NaturalVibe(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.NaturalVibe_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NaturalVibe obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_NaturalVibe(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public NaturalVibe(Model model, int nat_il, int nat_iu, double eigen_fac) {
    this(karambaJNI.new_NaturalVibe__SWIG_1(Model.getCPtr(model), model, nat_il, nat_iu, eigen_fac), true);
  }

  public NaturalVibe(Model model, int nat_il, int nat_iu) {
    this(karambaJNI.new_NaturalVibe__SWIG_2(Model.getCPtr(model), model, nat_il, nat_iu), true);
  }

  public NaturalVibe(Model model, int eigen_il, int eigen_iu, int max_iter, double eps, int sign, double eigen_fac) {
    this(karambaJNI.new_NaturalVibe__SWIG_3(Model.getCPtr(model), model, eigen_il, eigen_iu, max_iter, eps, sign, eigen_fac), true);
  }

  public NaturalVibe(NaturalVibe arg) {
    this(karambaJNI.new_NaturalVibe__SWIG_4(NaturalVibe.getCPtr(arg), arg), true);
  }

  public Deform clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.NaturalVibe_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new NaturalVibe(cPtr, false);
  }

  public Deform clone() {
    long cPtr = karambaJNI.NaturalVibe_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new NaturalVibe(cPtr, false);
  }

  public void copy(Deform orig) {
    karambaJNI.NaturalVibe_copy(swigCPtr, this, Deform.getCPtr(orig), orig);
  }

  public int analyze() {
    return karambaJNI.NaturalVibe_analyze(swigCPtr, this);
  }

  public VectReal naturalFrequencies() {
    return new VectReal(karambaJNI.NaturalVibe_naturalFrequencies(swigCPtr, this), true);
  }

  public VectReal modalMass() {
    return new VectReal(karambaJNI.NaturalVibe_modalMass(swigCPtr, this), false);
  }

  public VectVec3d partCoeff() {
    return new VectVec3d(karambaJNI.NaturalVibe_partCoeff(swigCPtr, this), false);
  }

}
