/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Surface3dFirstPrincipalKapa extends Surface3DVecEvalStrategy {
  private long swigCPtr;

  protected Surface3dFirstPrincipalKapa(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Surface3dFirstPrincipalKapa_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Surface3dFirstPrincipalKapa obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Surface3dFirstPrincipalKapa(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Surface3dFirstPrincipalKapa(long lc) {
    this(karambaJNI.new_Surface3dFirstPrincipalKapa(lc), true);
  }

  public SWIGTYPE_p_tvmet__VectorT_real_2_t res(TriShell3D elem) {
    return new SWIGTYPE_p_tvmet__VectorT_real_2_t(karambaJNI.Surface3dFirstPrincipalKapa_res(swigCPtr, this, TriShell3D.getCPtr(elem), elem), true);
  }

}
