/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class TriStreamTriangle2ndOrder extends TriStreamTriangle {
  private long swigCPtr;

  protected TriStreamTriangle2ndOrder(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.TriStreamTriangle2ndOrder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TriStreamTriangle2ndOrder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_TriStreamTriangle2ndOrder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TriStreamTriangle2ndOrder(TriFace face, long elem_ind, VectSizeT node_ind, VectVec3d updated_nodal_pos) {
    this(karambaJNI.new_TriStreamTriangle2ndOrder(TriFace.getCPtr(face), face, elem_ind, VectSizeT.getCPtr(node_ind), node_ind, VectVec3d.getCPtr(updated_nodal_pos), updated_nodal_pos), true);
  }

}
