/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Stitch extends GeMapping {
  private long swigCPtr;

  protected Stitch(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Stitch_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Stitch obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Stitch(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Stitch(long n_connections, ElementStraightLine elem) {
    this(karambaJNI.new_Stitch__SWIG_1(n_connections, ElementStraightLine.getCPtr(elem), elem), true);
  }

  public Stitch(SWIGTYPE_p_std__vectorT_PolyElement_p_t edges, long n_connections, ElementStraightLine elem) {
    this(karambaJNI.new_Stitch__SWIG_2(SWIGTYPE_p_std__vectorT_PolyElement_p_t.getCPtr(edges), n_connections, ElementStraightLine.getCPtr(elem), elem), true);
  }

  public Stitch(Stitch arg) {
    this(karambaJNI.new_Stitch__SWIG_3(Stitch.getCPtr(arg), arg), true);
  }

  public GeMapping clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Stitch_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Stitch(cPtr, false);
  }

  public GeMapping clone() {
    long cPtr = karambaJNI.Stitch_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Stitch(cPtr, false);
  }

  public void copy(Stitch orig) {
    karambaJNI.Stitch_copy(swigCPtr, this, Stitch.getCPtr(orig), orig);
  }

  public void addEdge(PolyElement edge) {
    karambaJNI.Stitch_addEdge(swigCPtr, this, PolyElement.getCPtr(edge), edge);
  }

  public long edgesCount() {
    return karambaJNI.Stitch_edgesCount(swigCPtr, this);
  }

  public SWIGTYPE_p_std__vectorT_PolyElement_p_t updatedEdges(Model femodel) {
    return new SWIGTYPE_p_std__vectorT_PolyElement_p_t(karambaJNI.Stitch_updatedEdges(swigCPtr, this, Model.getCPtr(femodel), femodel), false);
  }

  public long parametersPerConnection() {
    return karambaJNI.Stitch_parametersPerConnection(swigCPtr, this);
  }

  public long numberOfParameters() {
    return karambaJNI.Stitch_numberOfParameters(swigCPtr, this);
  }

  public void map(GeModel gemodel, SWIGTYPE_p_std__vectorT_double_t__const_iterator params_begin, SWIGTYPE_p_std__vectorT_double_t__const_iterator params_end) {
    karambaJNI.Stitch_map(swigCPtr, this, GeModel.getCPtr(gemodel), gemodel, SWIGTYPE_p_std__vectorT_double_t__const_iterator.getCPtr(params_begin), SWIGTYPE_p_std__vectorT_double_t__const_iterator.getCPtr(params_end));
  }

}
