/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Truss3DCroSec extends ElementCroSec {
  private long swigCPtr;

  protected Truss3DCroSec(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Truss3DCroSec_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Truss3DCroSec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Truss3DCroSec(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setA(double value) {
    karambaJNI.Truss3DCroSec_A_set(swigCPtr, this, value);
  }

  public double getA() {
    return karambaJNI.Truss3DCroSec_A_get(swigCPtr, this);
  }

  public Truss3DCroSec() {
    this(karambaJNI.new_Truss3DCroSec__SWIG_0(), true);
  }

  public Truss3DCroSec(double A) {
    this(karambaJNI.new_Truss3DCroSec__SWIG_1(A), true);
  }

  public Truss3DCroSec(Truss3DCroSec arg) {
    this(karambaJNI.new_Truss3DCroSec__SWIG_2(Truss3DCroSec.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Truss3DCroSec_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Truss3DCroSec(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.Truss3DCroSec_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Truss3DCroSec(cPtr, false);
  }

  public void copy(ElementCroSec orig) {
    karambaJNI.Truss3DCroSec_copy(swigCPtr, this, ElementCroSec.getCPtr(orig), orig);
  }

}
