/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Spring3DProperties extends ElementCroSec {
  private long swigCPtr;

  protected Spring3DProperties(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Spring3DProperties_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Spring3DProperties obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Spring3DProperties(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Spring3DProperties() {
    this(karambaJNI.new_Spring3DProperties__SWIG_0(), true);
  }

  public Spring3DProperties(VectReal c) {
    this(karambaJNI.new_Spring3DProperties__SWIG_1(VectReal.getCPtr(c), c), true);
  }

  public Spring3DProperties(double ctx, double cty, double ctz, double crx, double cry, double crz) {
    this(karambaJNI.new_Spring3DProperties__SWIG_2(ctx, cty, ctz, crx, cry, crz), true);
  }

  public Spring3DProperties(double ctx, double cty, double ctz, double crx, double cry) {
    this(karambaJNI.new_Spring3DProperties__SWIG_3(ctx, cty, ctz, crx, cry), true);
  }

  public Spring3DProperties(double ctx, double cty, double ctz, double crx) {
    this(karambaJNI.new_Spring3DProperties__SWIG_4(ctx, cty, ctz, crx), true);
  }

  public Spring3DProperties(double ctx, double cty, double ctz) {
    this(karambaJNI.new_Spring3DProperties__SWIG_5(ctx, cty, ctz), true);
  }

  public Spring3DProperties(double ctx, double cty) {
    this(karambaJNI.new_Spring3DProperties__SWIG_6(ctx, cty), true);
  }

  public Spring3DProperties(double ctx) {
    this(karambaJNI.new_Spring3DProperties__SWIG_7(ctx), true);
  }

  public Spring3DProperties(Spring3DProperties arg) {
    this(karambaJNI.new_Spring3DProperties__SWIG_8(Spring3DProperties.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Spring3DProperties_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Spring3DProperties(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.Spring3DProperties_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Spring3DProperties(cPtr, false);
  }

  public void copy(ElementCroSec orig) {
    karambaJNI.Spring3DProperties_copy(swigCPtr, this, ElementCroSec.getCPtr(orig), orig);
  }

  public VectReal c() {
    return new VectReal(karambaJNI.Spring3DProperties_c(swigCPtr, this), false);
  }

}
