/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class CroSecStateImp_LinearElastic_Beam_EC3 extends CroSecStateImp {
  private long swigCPtr;

  protected CroSecStateImp_LinearElastic_Beam_EC3(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.CroSecStateImp_LinearElastic_Beam_EC3_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CroSecStateImp_LinearElastic_Beam_EC3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_CroSecStateImp_LinearElastic_Beam_EC3(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CroSecStateImp_LinearElastic_Beam_EC3(double gamma_m0, double gamma_m1, double zg, double eps) {
    this(karambaJNI.new_CroSecStateImp_LinearElastic_Beam_EC3__SWIG_0(gamma_m0, gamma_m1, zg, eps), true);
  }

  public CroSecStateImp_LinearElastic_Beam_EC3(double gamma_m0, double gamma_m1, double zg) {
    this(karambaJNI.new_CroSecStateImp_LinearElastic_Beam_EC3__SWIG_1(gamma_m0, gamma_m1, zg), true);
  }

  public CroSecStateImp_LinearElastic_Beam_EC3(double gamma_m0, double gamma_m1) {
    this(karambaJNI.new_CroSecStateImp_LinearElastic_Beam_EC3__SWIG_2(gamma_m0, gamma_m1), true);
  }

  public CroSecStateImp_LinearElastic_Beam_EC3(double gamma_m0) {
    this(karambaJNI.new_CroSecStateImp_LinearElastic_Beam_EC3__SWIG_3(gamma_m0), true);
  }

  public CroSecStateImp_LinearElastic_Beam_EC3() {
    this(karambaJNI.new_CroSecStateImp_LinearElastic_Beam_EC3__SWIG_4(), true);
  }

  public CroSecStateImp clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.CroSecStateImp_LinearElastic_Beam_EC3_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new CroSecStateImp_LinearElastic_Beam_EC3(cPtr, false);
  }

  public CroSecStateImp clone() {
    long cPtr = karambaJNI.CroSecStateImp_LinearElastic_Beam_EC3_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new CroSecStateImp_LinearElastic_Beam_EC3(cPtr, false);
  }

  public void accept(CroSecStateVisitor visitor) {
    karambaJNI.CroSecStateImp_LinearElastic_Beam_EC3_accept(swigCPtr, this, CroSecStateVisitor.getCPtr(visitor), visitor);
  }

  public double utilization(Element elem, ActionVisitor action, BucklingLength bkl_len, ElementCroSec crosec, boolean can_buckle) {
    return karambaJNI.CroSecStateImp_LinearElastic_Beam_EC3_utilization(swigCPtr, this, Element.getCPtr(elem), elem, ActionVisitor.getCPtr(action), action, BucklingLength.getCPtr(bkl_len), bkl_len, ElementCroSec.getCPtr(crosec), crosec, can_buckle);
  }

  public UtilDetailsEC3 utilization_details() {
    return new UtilDetailsEC3(karambaJNI.CroSecStateImp_LinearElastic_Beam_EC3_utilization_details(swigCPtr, this), false);
  }

  public CalcDetailsEC3 calculation_details() {
    return new CalcDetailsEC3(karambaJNI.CroSecStateImp_LinearElastic_Beam_EC3_calculation_details(swigCPtr, this), false);
  }

}
