/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public final class SurfaceResultTag {
  public final static SurfaceResultTag eps1 = new SurfaceResultTag("eps1");
  public final static SurfaceResultTag eps2 = new SurfaceResultTag("eps2");
  public final static SurfaceResultTag sig1 = new SurfaceResultTag("sig1");
  public final static SurfaceResultTag sig2 = new SurfaceResultTag("sig2");
  public final static SurfaceResultTag sigV = new SurfaceResultTag("sigV");
  public final static SurfaceResultTag epsPrinc = new SurfaceResultTag("epsPrinc");
  public final static SurfaceResultTag sigPrinc = new SurfaceResultTag("sigPrinc");
  public final static SurfaceResultTag disp = new SurfaceResultTag("disp");
  public final static SurfaceResultTag util = new SurfaceResultTag("util");
  public final static SurfaceResultTag m1 = new SurfaceResultTag("m1");
  public final static SurfaceResultTag m2 = new SurfaceResultTag("m2");
  public final static SurfaceResultTag thickness = new SurfaceResultTag("thickness");
  public final static SurfaceResultTag nRes = new SurfaceResultTag("nRes");
  public final static SurfaceResultTag mRes = new SurfaceResultTag("mRes");
  public final static SurfaceResultTag vRes = new SurfaceResultTag("vRes");
  public final static SurfaceResultTag displaced_position = new SurfaceResultTag("displaced_position");
  public final static SurfaceResultTag sigV_signed = new SurfaceResultTag("sigV_signed");
  public final static SurfaceResultTag util_signed = new SurfaceResultTag("util_signed");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SurfaceResultTag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SurfaceResultTag.class + " with value " + swigValue);
  }

  private SurfaceResultTag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SurfaceResultTag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SurfaceResultTag(String swigName, SurfaceResultTag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SurfaceResultTag[] swigValues = { eps1, eps2, sig1, sig2, sigV, epsPrinc, sigPrinc, disp, util, m1, m2, thickness, nRes, mRes, vRes, displaced_position, sigV_signed, util_signed };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

