/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class VectCroSec {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public VectCroSec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectCroSec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_VectCroSec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectCroSec() {
    this(karambaJNI.new_VectCroSec__SWIG_0(), true);
  }

  public VectCroSec(long n) {
    this(karambaJNI.new_VectCroSec__SWIG_1(n), true);
  }

  public long size() {
    return karambaJNI.VectCroSec_size(swigCPtr, this);
  }

  public long capacity() {
    return karambaJNI.VectCroSec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    karambaJNI.VectCroSec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return karambaJNI.VectCroSec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    karambaJNI.VectCroSec_clear(swigCPtr, this);
  }

  public void add(ElementCroSec x) {
    karambaJNI.VectCroSec_add(swigCPtr, this, ElementCroSec.getCPtr(x), x);
  }

  public ElementCroSec get(int i) {
    long cPtr = karambaJNI.VectCroSec_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ElementCroSec(cPtr, false);
  }

  public void set(int i, ElementCroSec val) {
    karambaJNI.VectCroSec_set(swigCPtr, this, i, ElementCroSec.getCPtr(val), val);
  }

}
