/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ElementDirectionStrategy {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public ElementDirectionStrategy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ElementDirectionStrategy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ElementDirectionStrategy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vec3d elementDir(long i) {
    return new Vec3d(karambaJNI.ElementDirectionStrategy_elementDir(swigCPtr, this, i), false);
  }

}
