/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Eccentricity extends DeepCloneable {
  private long swigCPtr;

  protected Eccentricity(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Eccentricity_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Eccentricity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Eccentricity(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Eccentricity(double x_g, double y_g, double z_g, double x_l, double y_l, double z_l) {
    this(karambaJNI.new_Eccentricity__SWIG_0(x_g, y_g, z_g, x_l, y_l, z_l), true);
  }

  public Eccentricity(double x_g, double y_g, double z_g, double x_l, double y_l) {
    this(karambaJNI.new_Eccentricity__SWIG_1(x_g, y_g, z_g, x_l, y_l), true);
  }

  public Eccentricity(double x_g, double y_g, double z_g, double x_l) {
    this(karambaJNI.new_Eccentricity__SWIG_2(x_g, y_g, z_g, x_l), true);
  }

  public Eccentricity(double x_g, double y_g, double z_g) {
    this(karambaJNI.new_Eccentricity__SWIG_3(x_g, y_g, z_g), true);
  }

  public Eccentricity(double x_g, double y_g) {
    this(karambaJNI.new_Eccentricity__SWIG_4(x_g, y_g), true);
  }

  public Eccentricity(double x_g) {
    this(karambaJNI.new_Eccentricity__SWIG_5(x_g), true);
  }

  public Eccentricity() {
    this(karambaJNI.new_Eccentricity__SWIG_6(), true);
  }

  public Eccentricity(Eccentricity arg) {
    this(karambaJNI.new_Eccentricity__SWIG_7(Eccentricity.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Eccentricity_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Eccentricity(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.Eccentricity_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Eccentricity(cPtr, false);
  }

  public void copy(Eccentricity orig) {
    karambaJNI.Eccentricity_copy(swigCPtr, this, Eccentricity.getCPtr(orig), orig);
  }

  public Vec3d ecc_global(SWIGTYPE_p_Mat33 tmat_l2g, ElementCroSec crosec) {
    return new Vec3d(karambaJNI.Eccentricity_ecc_global(swigCPtr, this, SWIGTYPE_p_Mat33.getCPtr(tmat_l2g), ElementCroSec.getCPtr(crosec), crosec), true);
  }

  public long ind(long new_ind) {
    return karambaJNI.Eccentricity_ind__SWIG_0(swigCPtr, this, new_ind);
  }

  public long ind() {
    return karambaJNI.Eccentricity_ind__SWIG_1(swigCPtr, this);
  }

}
