/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class TriFaceInfo {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public TriFaceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(TriFaceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_TriFaceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLocalPos(VectVec3d value) {
    karambaJNI.TriFaceInfo_localPos_set(swigCPtr, this, VectVec3d.getCPtr(value), value);
  }

  public VectVec3d getLocalPos() {
    long cPtr = karambaJNI.TriFaceInfo_localPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectVec3d(cPtr, false);
  }

  public void setEdgeVec(VectVec3d value) {
    karambaJNI.TriFaceInfo_edgeVec_set(swigCPtr, this, VectVec3d.getCPtr(value), value);
  }

  public VectVec3d getEdgeVec() {
    long cPtr = karambaJNI.TriFaceInfo_edgeVec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectVec3d(cPtr, false);
  }

  public void setEdgeUnitVec(VectVec3d value) {
    karambaJNI.TriFaceInfo_edgeUnitVec_set(swigCPtr, this, VectVec3d.getCPtr(value), value);
  }

  public VectVec3d getEdgeUnitVec() {
    long cPtr = karambaJNI.TriFaceInfo_edgeUnitVec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectVec3d(cPtr, false);
  }

  public void setEdgeLength(VectReal value) {
    karambaJNI.TriFaceInfo_edgeLength_set(swigCPtr, this, VectReal.getCPtr(value), value);
  }

  public VectReal getEdgeLength() {
    long cPtr = karambaJNI.TriFaceInfo_edgeLength_get(swigCPtr, this);
    return (cPtr == 0) ? null : new VectReal(cPtr, false);
  }

  public TriFaceInfo() {
    this(karambaJNI.new_TriFaceInfo(), true);
  }

}
