/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class VectMaterial {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public VectMaterial(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectMaterial obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_VectMaterial(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectMaterial() {
    this(karambaJNI.new_VectMaterial__SWIG_0(), true);
  }

  public VectMaterial(long n) {
    this(karambaJNI.new_VectMaterial__SWIG_1(n), true);
  }

  public long size() {
    return karambaJNI.VectMaterial_size(swigCPtr, this);
  }

  public long capacity() {
    return karambaJNI.VectMaterial_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    karambaJNI.VectMaterial_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return karambaJNI.VectMaterial_isEmpty(swigCPtr, this);
  }

  public void clear() {
    karambaJNI.VectMaterial_clear(swigCPtr, this);
  }

  public void add(Material x) {
    karambaJNI.VectMaterial_add(swigCPtr, this, Material.getCPtr(x), x);
  }

  public Material get(int i) {
    long cPtr = karambaJNI.VectMaterial_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Material(cPtr, false);
  }

  public void set(int i, Material val) {
    karambaJNI.VectMaterial_set(swigCPtr, this, i, Material.getCPtr(val), val);
  }

}
