/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class VectVec3d {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public VectVec3d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(VectVec3d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_VectVec3d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectVec3d() {
    this(karambaJNI.new_VectVec3d__SWIG_0(), true);
  }

  public VectVec3d(long n) {
    this(karambaJNI.new_VectVec3d__SWIG_1(n), true);
  }

  public long size() {
    return karambaJNI.VectVec3d_size(swigCPtr, this);
  }

  public long capacity() {
    return karambaJNI.VectVec3d_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    karambaJNI.VectVec3d_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return karambaJNI.VectVec3d_isEmpty(swigCPtr, this);
  }

  public void clear() {
    karambaJNI.VectVec3d_clear(swigCPtr, this);
  }

  public void add(Vec3d x) {
    karambaJNI.VectVec3d_add(swigCPtr, this, Vec3d.getCPtr(x), x);
  }

  public Vec3d get(int i) {
    return new Vec3d(karambaJNI.VectVec3d_get(swigCPtr, this, i), false);
  }

  public void set(int i, Vec3d val) {
    karambaJNI.VectVec3d_set(swigCPtr, this, i, Vec3d.getCPtr(val), val);
  }

}
