/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class weightingInfo {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public weightingInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(weightingInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_weightingInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public weightingInfo(double t, double c, double s, double m) {
    this(karambaJNI.new_weightingInfo(t, c, s, m), true);
  }

  public void setFac_tension(double value) {
    karambaJNI.weightingInfo_fac_tension_set(swigCPtr, this, value);
  }

  public double getFac_tension() {
    return karambaJNI.weightingInfo_fac_tension_get(swigCPtr, this);
  }

  public void setFac_compression(double value) {
    karambaJNI.weightingInfo_fac_compression_set(swigCPtr, this, value);
  }

  public double getFac_compression() {
    return karambaJNI.weightingInfo_fac_compression_get(swigCPtr, this);
  }

  public void setFac_shear(double value) {
    karambaJNI.weightingInfo_fac_shear_set(swigCPtr, this, value);
  }

  public double getFac_shear() {
    return karambaJNI.weightingInfo_fac_shear_get(swigCPtr, this);
  }

  public void setFac_moment(double value) {
    karambaJNI.weightingInfo_fac_moment_set(swigCPtr, this, value);
  }

  public double getFac_moment() {
    return karambaJNI.weightingInfo_fac_moment_get(swigCPtr, this);
  }

}
