/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Beam3DCroSec extends Truss3DCroSec {
  private long swigCPtr;

  protected Beam3DCroSec(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.Beam3DCroSec_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Beam3DCroSec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Beam3DCroSec(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Beam3DCroSec() {
    this(karambaJNI.new_Beam3DCroSec__SWIG_0(), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt, double Ay_, double Az_, double Cw, double alpha_LT) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_1(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt, Ay_, Az_, Cw, alpha_LT), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt, double Ay_, double Az_, double Cw) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_2(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt, Ay_, Az_, Cw), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt, double Ay_, double Az_) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_3(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt, Ay_, Az_), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt, double Ay_) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_4(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt, Ay_), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz, double Wt) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_5(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz, Wt), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply, double Wplz) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_6(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply, Wplz), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z, double Wply) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_7(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z, Wply), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y, double alpha_z) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_8(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y, alpha_z), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz, double alpha_y) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_9(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz, alpha_y), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz, double iz) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_10(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz, iz), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy, double Welz) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_11(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy, Welz), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely, double iy) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_12(A, Iyy, Izz, Ipp, ky, kz, _group, Wely, iy), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group, double Wely) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_13(A, Iyy, Izz, Ipp, ky, kz, _group, Wely), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz, int _group) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_14(A, Iyy, Izz, Ipp, ky, kz, _group), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky, double kz) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_15(A, Iyy, Izz, Ipp, ky, kz), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp, double ky) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_16(A, Iyy, Izz, Ipp, ky), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz, double Ipp) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_17(A, Iyy, Izz, Ipp), true);
  }

  public Beam3DCroSec(double A, double Iyy, double Izz) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_18(A, Iyy, Izz), true);
  }

  public Beam3DCroSec(Beam3DCroSec arg) {
    this(karambaJNI.new_Beam3DCroSec__SWIG_19(Beam3DCroSec.getCPtr(arg), arg), true);
  }

  public DeepCloneable clone(SWIGTYPE_p_std__mapT_void_const_p_void_p_t mapDict) {
    long cPtr = karambaJNI.Beam3DCroSec_clone__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__mapT_void_const_p_void_p_t.getCPtr(mapDict));
    return (cPtr == 0) ? null : new Beam3DCroSec(cPtr, false);
  }

  public DeepCloneable clone() {
    long cPtr = karambaJNI.Beam3DCroSec_clone__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new Beam3DCroSec(cPtr, false);
  }

  public void copy(ElementCroSec orig) {
    karambaJNI.Beam3DCroSec_copy(swigCPtr, this, ElementCroSec.getCPtr(orig), orig);
  }

  public boolean strongerThan(ElementCroSec other) {
    return karambaJNI.Beam3DCroSec_strongerThan(swigCPtr, this, ElementCroSec.getCPtr(other), other);
  }

  public boolean isHollow() {
    return karambaJNI.Beam3DCroSec_isHollow(swigCPtr, this);
  }

  public void setIyy(double value) {
    karambaJNI.Beam3DCroSec_Iyy_set(swigCPtr, this, value);
  }

  public double getIyy() {
    return karambaJNI.Beam3DCroSec_Iyy_get(swigCPtr, this);
  }

  public void setIzz(double value) {
    karambaJNI.Beam3DCroSec_Izz_set(swigCPtr, this, value);
  }

  public double getIzz() {
    return karambaJNI.Beam3DCroSec_Izz_get(swigCPtr, this);
  }

  public void setIpp(double value) {
    karambaJNI.Beam3DCroSec_Ipp_set(swigCPtr, this, value);
  }

  public double getIpp() {
    return karambaJNI.Beam3DCroSec_Ipp_get(swigCPtr, this);
  }

  public void setCw(double value) {
    karambaJNI.Beam3DCroSec_Cw_set(swigCPtr, this, value);
  }

  public double getCw() {
    return karambaJNI.Beam3DCroSec_Cw_get(swigCPtr, this);
  }

  public void setKy(double value) {
    karambaJNI.Beam3DCroSec_ky_set(swigCPtr, this, value);
  }

  public double getKy() {
    return karambaJNI.Beam3DCroSec_ky_get(swigCPtr, this);
  }

  public void setKz(double value) {
    karambaJNI.Beam3DCroSec_kz_set(swigCPtr, this, value);
  }

  public double getKz() {
    return karambaJNI.Beam3DCroSec_kz_get(swigCPtr, this);
  }

  public void setWely(double value) {
    karambaJNI.Beam3DCroSec_Wely_set(swigCPtr, this, value);
  }

  public double getWely() {
    return karambaJNI.Beam3DCroSec_Wely_get(swigCPtr, this);
  }

  public void setWply(double value) {
    karambaJNI.Beam3DCroSec_Wply_set(swigCPtr, this, value);
  }

  public double getWply() {
    return karambaJNI.Beam3DCroSec_Wply_get(swigCPtr, this);
  }

  public void setIy(double value) {
    karambaJNI.Beam3DCroSec_iy_set(swigCPtr, this, value);
  }

  public double getIy() {
    return karambaJNI.Beam3DCroSec_iy_get(swigCPtr, this);
  }

  public void setWelz(double value) {
    karambaJNI.Beam3DCroSec_Welz_set(swigCPtr, this, value);
  }

  public double getWelz() {
    return karambaJNI.Beam3DCroSec_Welz_get(swigCPtr, this);
  }

  public void setWplz(double value) {
    karambaJNI.Beam3DCroSec_Wplz_set(swigCPtr, this, value);
  }

  public double getWplz() {
    return karambaJNI.Beam3DCroSec_Wplz_get(swigCPtr, this);
  }

  public void setIz(double value) {
    karambaJNI.Beam3DCroSec_iz_set(swigCPtr, this, value);
  }

  public double getIz() {
    return karambaJNI.Beam3DCroSec_iz_get(swigCPtr, this);
  }

  public void setAlpha_y(double value) {
    karambaJNI.Beam3DCroSec_alpha_y_set(swigCPtr, this, value);
  }

  public double getAlpha_y() {
    return karambaJNI.Beam3DCroSec_alpha_y_get(swigCPtr, this);
  }

  public void setAlpha_z(double value) {
    karambaJNI.Beam3DCroSec_alpha_z_set(swigCPtr, this, value);
  }

  public double getAlpha_z() {
    return karambaJNI.Beam3DCroSec_alpha_z_get(swigCPtr, this);
  }

  public void setAlpha_LT(double value) {
    karambaJNI.Beam3DCroSec_alpha_LT_set(swigCPtr, this, value);
  }

  public double getAlpha_LT() {
    return karambaJNI.Beam3DCroSec_alpha_LT_get(swigCPtr, this);
  }

  public void setWt(double value) {
    karambaJNI.Beam3DCroSec_Wt_set(swigCPtr, this, value);
  }

  public double getWt() {
    return karambaJNI.Beam3DCroSec_Wt_get(swigCPtr, this);
  }

  public void setAy(double value) {
    karambaJNI.Beam3DCroSec_Ay_set(swigCPtr, this, value);
  }

  public double getAy() {
    return karambaJNI.Beam3DCroSec_Ay_get(swigCPtr, this);
  }

  public void setAz(double value) {
    karambaJNI.Beam3DCroSec_Az_set(swigCPtr, this, value);
  }

  public double getAz() {
    return karambaJNI.Beam3DCroSec_Az_get(swigCPtr, this);
  }

  public long croSecClass(double Ncompr, double My, double Mz, double eps) {
    return karambaJNI.Beam3DCroSec_croSecClass(swigCPtr, this, Ncompr, My, Mz, eps);
  }

}
