/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class ElemSLDimPlastic extends ElemSLDimElastic {
  private long swigCPtr;

  protected ElemSLDimPlastic(long cPtr, boolean cMemoryOwn) {
    super(karambaJNI.ElemSLDimPlastic_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ElemSLDimPlastic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_ElemSLDimPlastic(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ElemSLDimPlastic(Response response, long max_ULS_design_iter, long max_SLS_design_iter, double lim_util, long n_samples) {
    this(karambaJNI.new_ElemSLDimPlastic__SWIG_0(Response.getCPtr(response), response, max_ULS_design_iter, max_SLS_design_iter, lim_util, n_samples), true);
  }

  public ElemSLDimPlastic(Response response, long max_ULS_design_iter, long max_SLS_design_iter, double lim_util) {
    this(karambaJNI.new_ElemSLDimPlastic__SWIG_1(Response.getCPtr(response), response, max_ULS_design_iter, max_SLS_design_iter, lim_util), true);
  }

  public ElemSLDimPlastic(Response response, long max_ULS_design_iter, long max_SLS_design_iter) {
    this(karambaJNI.new_ElemSLDimPlastic__SWIG_2(Response.getCPtr(response), response, max_ULS_design_iter, max_SLS_design_iter), true);
  }

  public ElemSLDimPlastic(Response response, long max_ULS_design_iter) {
    this(karambaJNI.new_ElemSLDimPlastic__SWIG_3(Response.getCPtr(response), response, max_ULS_design_iter), true);
  }

  public ElemSLDimPlastic(Response response) {
    this(karambaJNI.new_ElemSLDimPlastic__SWIG_4(Response.getCPtr(response), response), true);
  }

}
