/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class FormFinder {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public FormFinder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FormFinder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_FormFinder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FormFinder(Model model, long n_load_inc) {
    this(karambaJNI.new_FormFinder__SWIG_0(Model.getCPtr(model), model, n_load_inc), true);
  }

  public FormFinder(Model model) {
    this(karambaJNI.new_FormFinder__SWIG_1(Model.getCPtr(model), model), true);
  }

  public void copy(FormFinder orig) {
    karambaJNI.FormFinder_copy(swigCPtr, this, FormFinder.getCPtr(orig), orig);
  }

  public void targetDeflection(double max_def) {
    karambaJNI.FormFinder_targetDeflection(swigCPtr, this, max_def);
  }

  public Model findForm() {
    long cPtr = karambaJNI.FormFinder_findForm(swigCPtr, this);
    return (cPtr == 0) ? null : new Model(cPtr, false);
  }

  public double maxTotDeflection() {
    return karambaJNI.FormFinder_maxTotDeflection(swigCPtr, this);
  }

  public Vec3d transformToGlobal(long node_ind, double x, double y, double z) {
    return new Vec3d(karambaJNI.FormFinder_transformToGlobal(swigCPtr, this, node_ind, x, y, z), true);
  }

}
