/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package feb;

public class Vec3d {
  private long swigCPtr;
  public boolean swigCMemOwn;

  public Vec3d(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vec3d obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        karambaJNI.delete_Vec3d(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vec3d() {
    this(karambaJNI.new_Vec3d__SWIG_0(), true);
  }

  public Vec3d(SWIGTYPE_p_VecReal v) {
    this(karambaJNI.new_Vec3d__SWIG_1(SWIGTYPE_p_VecReal.getCPtr(v)), true);
  }

  public Vec3d(double x, double y, double z) {
    this(karambaJNI.new_Vec3d__SWIG_3(x, y, z), true);
  }

  public Vec3d clone() {
    long cPtr = karambaJNI.Vec3d_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Vec3d(cPtr, false);
  }

  public void clear() {
    karambaJNI.Vec3d_clear(swigCPtr, this);
  }

  public double squaredLength() {
    return karambaJNI.Vec3d_squaredLength(swigCPtr, this);
  }

  public double Length() {
    return karambaJNI.Vec3d_Length(swigCPtr, this);
  }

  public void add(Vec3d v) {
    karambaJNI.Vec3d_add(swigCPtr, this, Vec3d.getCPtr(v), v);
  }

  public void scale(double s) {
    karambaJNI.Vec3d_scale(swigCPtr, this, s);
  }

  public double x() {
    return karambaJNI.Vec3d_x__SWIG_0(swigCPtr, this);
  }

  public double x(double v) {
    return karambaJNI.Vec3d_x__SWIG_1(swigCPtr, this, v);
  }

  public double y() {
    return karambaJNI.Vec3d_y__SWIG_0(swigCPtr, this);
  }

  public double y(double v) {
    return karambaJNI.Vec3d_y__SWIG_1(swigCPtr, this, v);
  }

  public double z() {
    return karambaJNI.Vec3d_z__SWIG_0(swigCPtr, this);
  }

  public double z(double v) {
    return karambaJNI.Vec3d_z__SWIG_1(swigCPtr, this, v);
  }

  public Vec3d princ() {
    return new Vec3d(karambaJNI.Vec3d_princ(swigCPtr, this), true);
  }

  public SWIGTYPE_p_tvmet__VectorT_real_2_t first_princ() {
    return new SWIGTYPE_p_tvmet__VectorT_real_2_t(karambaJNI.Vec3d_first_princ(swigCPtr, this), true);
  }

  public SWIGTYPE_p_tvmet__VectorT_real_2_t second_princ() {
    return new SWIGTYPE_p_tvmet__VectorT_real_2_t(karambaJNI.Vec3d_second_princ(swigCPtr, this), true);
  }

  public double vanMises() {
    return karambaJNI.Vec3d_vanMises(swigCPtr, this);
  }

}
